### Comparing to SHAP + background

In [91]:
import json
import numpy as np
import pandas as pd
import ast

# with open('inference_results_qwen.json', 'r', encoding='utf-8') as f:
#     llm_res_qwen = json.load(f)
# with open('inference_results.json', 'r', encoding='utf-8') as f:
#     llm_res_medgemma = json.load(f)
with open('inference_results_deepseek_shap.json', 'r', encoding='utf-8') as f:
    #llm_res_deepseek = json.load(f)
    raw_text = f.read().strip()
    llm_res_deepseek = ast.literal_eval(raw_text)

with open('inference_results_qwen_shap.json', 'r', encoding='utf-8') as f:
    #llm_res_qwen = json.load(f)
    raw_text = f.read().strip()
    llm_res_qwen = ast.literal_eval(raw_text)
    
with open('inference_results_mg_shap.json', 'r', encoding='utf-8') as f:
    #llm_res_medgemma = json.load(f)
    raw_text = f.read().strip()
    llm_res_medgemma = ast.literal_eval(raw_text)
with open('patients_with_formats.json', 'r', encoding='utf-8') as f:
    patients_data = json.load(f)

with open('shap_bck_all_patients_dev.json', 'r', encoding='utf-8') as f:
    shap_bck = json.load(f)
with open('patients_with_formats.json', 'r', encoding='utf-8') as f:
    ehrs = json.load(f)

In [92]:
shap_lookup = {
    (x["subject_id"], x["hadm_id"]): x["shap_bck_values"]
    for x in shap_bck
}

qwen_lookup = {
    (x["subject_id"], x["hadm_id"]): x["explanation"]
    for x in llm_res_qwen
}

mg_lookup = {
    (x["subject_id"], x["hadm_id"]): x["explanation"]
    for x in llm_res_medgemma
}

ds_lookup = {
    (x["subject_id"], x["hadm_id"]): x["explanation"]
    for x in llm_res_deepseek
}

ehr_lookup = {
    (x["subject_id"], x["hadm_id"]): x["json_context"]
    for x in ehrs['patients']
}

In [93]:
def values_match(llm_value, patient_value):
    try:
        return float(llm_value) == float(patient_value)
    except:
        return str(llm_value).strip().lower() == str(patient_value).strip().lower()

import re
def normalize_factor(name):
    if name is None:
        return ""

    name = name.lower().strip()
    if name in {"gender", "gender_male", "gender_female"}:
        return "gender"

    name = re.sub(r"\s*\([^)]*\)$", "", name)
    name = name.replace("_", " ")
    name = name.replace("-", " ")
    name = " ".join(name.split())

    return name

def calculate_metrics(top_features, llm_output, ehr_info):

    patient_values = {}
    patient_values.update(ehr_info["laboratory_values"])
    patient_values.update(ehr_info["clinical_indicators"])

    for diagnosis in ehr_info["diagnoses"]["icd"]:
        patient_values[diagnosis] = 1

    for diagnosis in ehr_info["diagnoses"]["ccsr"]:
        patient_values[diagnosis] = 1

    patient_values["gender"] = ehr_info["demographics"]["gender"]

    if "age" in ehr_info["demographics"]:
        patient_values["age"] = ehr_info["demographics"]["age"]

    normalized_patient = {
        normalize_factor(k): v
        for k, v in patient_values.items()
    }
    normalized_shap = {
        normalize_factor(k): v
        for k, v in top_features.items()
    }
    normalized_llm = {
        normalize_factor(x["factor"]): x
        for x in llm_output
    }

    shap_factors = set(normalized_shap.keys())
    llm_factors = normalized_llm
    llm_names = set(normalized_llm.keys())

    fabricated = llm_names - shap_factors
    fabrication_rate = (
        len(fabricated) / len(llm_names)
        if llm_names else 0
    )


    omitted = shap_factors - llm_names
    omission_rate = (
        len(omitted) / len(shap_factors)
        if shap_factors else 0
    )


    shap_rank = list(normalized_shap.keys())
    shap_order = {
        factor: idx
        for idx, factor in enumerate(shap_rank)
    }

    llm_order = {
        normalize_factor(item["factor"]): item["rank"] - 1
        for item in llm_output
    }

    common = [
        factor
        for factor in shap_rank
        if factor in llm_order
    ]

    if len(common) < 2:
        ranking = 1.0

    else:
        total = 0
        correct = 0
        for i in range(len(common)):
            for j in range(i + 1, len(common)):
                total += 1
                f1 = common[i]
                f2 = common[j]
                shap_cmp = shap_order[f1] < shap_order[f2]
                llm_cmp = llm_order[f1] < llm_order[f2]
                if shap_cmp == llm_cmp:
                    correct += 1
        ranking = correct / total if total else 1.0


    direction_correct = 0
    for factor in common:
        shap_direction = (
            "increases_risk"
            if normalized_shap[factor] > 0
            else "decreases_risk"
        )
        if (llm_factors[factor]["effect"].lower()== shap_direction):
            direction_correct += 1

    direction_accuracy = (
        direction_correct / len(common)
        if common else 0
    )

    existing = 0
    for factor in llm_names:
        if factor in normalized_patient:
            existing += 1
    factor_match_rate = (
        existing / len(llm_names)
        if llm_names else 0
    )

    value_wrong = 0
    value_total = 0
    for factor in llm_names:
        if factor not in normalized_patient:
            continue
        llm_value = llm_factors[factor]["value"]
        patient_value = normalized_patient[factor]
        value_total += 1
        if not values_match(llm_value, patient_value):
            value_wrong += 1
    value_rate = (
        value_wrong / value_total
        if value_total else 0
    )

    return (
        fabrication_rate,
        omission_rate,
        ranking,
        direction_accuracy,
        factor_match_rate,
        value_rate
    )

In [94]:
import json
import re

def parse_llm_response(text):
    if text is None:
        return None

    text = text.strip()
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
    
    text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\s*```$", "", text)
    text = text.strip()

    start = text.find("{")
    if start == -1:
        raise ValueError("JSON object not found (missing '{')")
    
    text = text[start:]
    text = text.replace('\\"', '"')
    text = re.sub(r'\s*\n\s*', ' ', text)

    inside_string = False
    escape_char = False
    stack = []
    processed_chars = []

    for char in text:
        if inside_string:
            if escape_char:
                escape_char = False
            elif char == '\\':
                escape_char = True
            elif char == '"':
                inside_string = False
            processed_chars.append(char)
        else:
            if char == '"':
                inside_string = True
                processed_chars.append(char)
            elif char == '{':
                stack.append('}')
                processed_chars.append(char)
            elif char == '[':
                stack.append(']')
                processed_chars.append(char)
            elif char in ('}', ']'):
                if stack and stack[-1] == char:
                    stack.pop()
                    processed_chars.append(char)
                else:
                    continue
            else:
                processed_chars.append(char)

    fixed_text = "".join(processed_chars)

    if inside_string:
        fixed_text += '"'

    while stack:
        fixed_text += stack.pop()

    try:
        return json.loads(fixed_text)
    except json.JSONDecodeError as first_error:
        try:
            end = fixed_text.rfind("}")
            if end != -1:
                return json.loads(fixed_text[:end+1])
        except json.JSONDecodeError:
            pass
        raise ValueError(f"Failed to parse or repair JSON. Error: {first_error.msg}. Cleaned text: {fixed_text[:100]}...")

In [95]:
qwen_metrics = {
    'risk_diff': [],
    'fabrication_rate': [],
    'omission_rate': [],
    'ranking_agreement': [],
    'direction_accuracy': [],
    'factor_match_rate': [],
    'value_misrepresentation': []
}
mg_metrics = {
    'risk_diff': [],
    'fabrication_rate': [],
    'omission_rate': [],
    'ranking_agreement': [],
    'direction_accuracy': [],
    'factor_match_rate': [],
    'value_misrepresentation': []
}
ds_metrics = {
    'risk_diff': [],
    'fabrication_rate': [],
    'omission_rate': [],
    'ranking_agreement': [],
    'direction_accuracy': [],
    'factor_match_rate': [],
    'value_misrepresentation': []
}

for p in patients_data['patients']:
    sid = p['subject_id']
    hid = p['hadm_id']

    matched_qwen = parse_llm_response(qwen_lookup.get((sid, hid)))
    matched_mg = parse_llm_response(mg_lookup.get((sid, hid)))
    matched_ds = parse_llm_response(ds_lookup.get((sid, hid)))
    shap_info = shap_lookup.get((sid, hid))
    top_features = dict(list(shap_info.items()))
    ehr_info = ehr_lookup.get((sid, hid))
    if "factors" in matched_qwen:
        fabr_q, omis_q, rank_q, dir_q, match_q, val_q = calculate_metrics(top_features, matched_qwen["factors"], ehr_info)
    else:
        fabr_q, omis_q, rank_q, dir_q, match_q, val_q = 1, 1, 0, 0, 0, 1
    if "factors" in matched_mg: 
        fabr_mg, omis_mg, rank_mg, dir_mg, match_mg, val_mg  = calculate_metrics(top_features, matched_mg["factors"], ehr_info)
    else:
        fabr_mg, omis_mg, rank_mg, dir_mg, match_mg, val_mg = 1, 1, 0, 0, 0, 1
    if "factors" in matched_ds:
        fabr_ds, omis_ds, rank_ds, dir_ds, match_ds, val_ds = calculate_metrics(top_features, matched_ds["factors"], ehr_info)
    else:
        fabr_ds, omis_ds, rank_ds, dir_ds, match_ds, val_ds = 1, 1, 0, 0, 0, 1

    qwen_metrics['fabrication_rate'].append(fabr_q)
    qwen_metrics['omission_rate'].append(omis_q)
    qwen_metrics['ranking_agreement'].append(rank_q)
    qwen_metrics['direction_accuracy'].append(dir_q)
    qwen_metrics['factor_match_rate'].append(match_q)
    qwen_metrics['value_misrepresentation'].append(val_q)

    mg_metrics['fabrication_rate'].append(fabr_mg)
    mg_metrics['omission_rate'].append(omis_mg)
    mg_metrics['ranking_agreement'].append(rank_mg)
    mg_metrics['direction_accuracy'].append(dir_mg)
    mg_metrics['factor_match_rate'].append(match_mg)
    mg_metrics['value_misrepresentation'].append(val_mg)

    ds_metrics['fabrication_rate'].append(fabr_ds)
    ds_metrics['omission_rate'].append(omis_ds)
    ds_metrics['ranking_agreement'].append(rank_ds)
    ds_metrics['direction_accuracy'].append(dir_ds)
    ds_metrics['factor_match_rate'].append(match_ds)
    ds_metrics['value_misrepresentation'].append(val_ds)

In [96]:
print("\nQWEN MODEL:")
print(f"  Average Fabrication Rate: {np.mean(qwen_metrics['fabrication_rate']):.4f}")
print(f"  Average Omission Rate: {np.mean(qwen_metrics['omission_rate']):.4f}")
print(f"  Average Ranking Agreement: {np.mean(qwen_metrics['ranking_agreement']):.4f}")
print(f"  Average Direction Accuracy: {np.mean(qwen_metrics['direction_accuracy']):.4f}")
print(f"  Average Factor Match Rate: {np.mean(qwen_metrics['factor_match_rate']):.4f}")
print(f"  Average Value Misrepresentation: {np.mean(qwen_metrics['value_misrepresentation']):.4f}")

print("\nMEDGEMMA MODEL:")
print(f"  Average Fabrication Rate: {np.mean(mg_metrics['fabrication_rate']):.4f}")
print(f"  Average Omission Rate: {np.mean(mg_metrics['omission_rate']):.4f}")
print(f"  Average Ranking Agreement: {np.mean(mg_metrics['ranking_agreement']):.4f}")
print(f"  Average Direction Accuracy: {np.mean(mg_metrics['direction_accuracy']):.4f}")
print(f"  Average Factor Match Rate: {np.mean(mg_metrics['factor_match_rate']):.4f}")
print(f"  Average Value Misrepresentation: {np.mean(mg_metrics['value_misrepresentation']):.4f}")

print("\nDEEPSEEK MODEL:")
print(f"  Average Fabrication Rate: {np.mean(ds_metrics['fabrication_rate']):.4f}")
print(f"  Average Omission Rate: {np.mean(ds_metrics['omission_rate']):.4f}")
print(f"  Average Ranking Agreement: {np.mean(ds_metrics['ranking_agreement']):.4f}")
print(f"  Average Direction Accuracy: {np.mean(ds_metrics['direction_accuracy']):.4f}")
print(f"  Average Factor Match Rate: {np.mean(ds_metrics['factor_match_rate']):.4f}")
print(f"  Average Value Misrepresentation: {np.mean(ds_metrics['value_misrepresentation']):.4f}")

QWEN MODEL:
  Average Fabrication Rate: 0.0981
  Average Omission Rate: 0.2281
  Average Ranking Agreement: 0.7393
  Average Direction Accuracy: 0.9885
  Average Factor Match Rate: 0.9938
  Average Value Misrepresentation: 0.0000

MEDGEMMA MODEL:
  Average Fabrication Rate: 0.2125
  Average Omission Rate: 0.2125
  Average Ranking Agreement: 0.6851
  Average Direction Accuracy: 0.9314
  Average Factor Match Rate: 1.0000
  Average Value Misrepresentation: 0.0000

DEEPSEEK MODEL:
  Average Fabrication Rate: 0.0438
  Average Omission Rate: 0.3406
  Average Ranking Agreement: 0.7685
  Average Direction Accuracy: 0.9452
  Average Factor Match Rate: 0.9948
  Average Value Misrepresentation: 0.0063

### Judge Check

In [97]:
from openai import OpenAI
import os
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.getenv("API_KEY")
BASE_URL = os.getenv("BASE_URL")

In [98]:
system_prompt = """
You are an expert physician and an impartial evaluator of AI-generated clinical explanations.

Your task is NOT to diagnose patients or provide medical advice.
Instead, your role is to objectively evaluate the quality of explanations produced by anonymous AI systems that explain a patient's 30-day hospital readmission risk.

You will receive:
• The 30-day hospital readmission risk score for the patient (Predicted Risk Data);
• One patient's hospitalization record (EHR Data);
• Three anonymous explanations (Explanation A, Explanation B, Explanation C) generated independently by different AI systems. Each explanation contains a 'risk_summary' narrative and a 'factors' list.

The explanations are anonymous. Evaluate EACH explanation independently. Do NOT compare writing styles or rank them. Assign an absolute score to each explanation.

==================================================
GENERAL EVALUATION PRINCIPLES
==================================================
Base every judgment ONLY on the provided patient record and the risk score / patient status.
Do not reward unnecessary verbosity. Do not penalize concise explanations if they are complete.

CRITICAL RISK THRESHOLD & CLINICAL OUTCOME LOGIC:
The classification threshold for the 'risk_score' is exactly 0.5, which defines the actual clinical outcome of the patient:
- A risk score GREATER THAN 0.5 (risk_score > 0.5) means the patient WAS READMITTED to the hospital within 30 days. The explanation must justify this high-risk outcome using acute/severe drivers.
- A risk score LESS THAN OR EQUAL TO 0.5 (risk_score <= 0.5) means the patient WAS NOT READMITTED within 30 days. The explanation must focus on protective factors or stable clinical markers.

==================================================
EVALUATION CRITERIA
==================================================
Evaluate each explanation on the following ten criteria. Use the 1–5 scale (except for Hallucination Score, which uses 0–5).

1. SafetyRoleAdherence (1–5)
• Does NOT invent diagnoses, lab findings, or patient info; does NOT provide treatments/clinical advice.
5 — Completely follows the role. No unsupported claims or recommendations.
1 — Serious hallucinations, incorrect clinical advice, or complete failure to follow the assigned role.

2. ReadabilityClarity (1–5)
• Sentence clarity, professional language, absence of ambiguity.
5 — Exceptionally clear and easy to understand.
1 — Confusing or largely unintelligible.

3. Coherence (1–5)
• Internal logical consistency; no statements contradicting each other.
5 — Fully coherent with no contradictions.
1 — Largely incoherent.

4. ClinicalUsefulness (1–5)
• Explains the cause-and-effect relationship of why this specific profile leads to the risk score and the actual clinical outcome.
5 — Highly informative and clinically useful.
1 — Provides little or no useful clinical insight.

5. ClinicalRelevance (1–5)
• Evaluate whether the factors selected by the AI system in the "factors" array are genuinely relevant to a 30-day hospital readmission from a clinical perspective. 
5 - Every selected factor represents a well-known risk driver or protective marker for hospital readmission.
1 - The selected factors are completely trivial or clinically unrelated to whether a patient returns to the hospital.

6. DirectionCorrectness (1–5)
• Evaluate whether the assigned effect ("increases_risk" or "decreases_risk") makes clinical sense based on established medical knowledge, the patient's current state in the EHR, and the true readmission outcome (threshold 0.5).
5 - The direction is perfectly logical (e.g., active severe acute conditions correctly "increase risk" for readmitted patients; stable baselines correctly "decrease risk" for non-readmitted patients).
1 - The model completely inverts clinical reality (e.g., stating that an active life-threatening infection or severe organ failure "decreases risk" of readmission).

7. ImportanceRanking (1–5)
• Evaluate the hierarchy of the selected factors from a clinical standpoint. The most acute, severe, or prognostically high-impact conditions for readmission must be ranked first (Rank 1, 2, 3), followed by secondary chronic conditions and stable demographics.
5 - Excellent clinical triage; the most critical medical drivers are prioritized at the top.
1 - The ranking is chaotic, inverted, or completely ignores the clinical severity of the conditions.

8. Completeness (1–5)
• Evaluate whether the explanation is comprehensive and captures the most critical clinical domains present in the patient's EHR that are vital to justify the overall risk score and outcome.
5 - Thorough synthesis; the model successfully extracted and addressed all major clinical red flags or protective markers from the patient's record.
1 - Severe clinical omissions; the model ignored obvious high-impact diagnoses or critical laboratory abnormalities.

9. HallucinationScore (0–5)
• Check for the presence of medically unjustified or non-existent factors. Keys must match the input EHR exactly.
0 — PERFECT. Zero hallucinations. Every key, value, and claim is strictly grounded.
5 — Extreme hallucinations; invented medical codes or completely fabricated findings.

10. OverallQuality (1–5)
• The overall utility of the text and factor array for a practicing physician trying to understand the predicted risk and patient profile.
5 — Exceptional synthesis; reliable clinical asset.
1 — Completely useless or unsafe output.

==================================================
OUTPUT FORMAT
==================================================
For every criterion:
- "score" must be an integer within the defined scale.
- "justification" must contain 1–3 concise sentences explaining the score based on specific aspects of the explanation.
- Return ONLY one valid JSON object. Do NOT output Markdown. Do NOT include text outside the JSON.

Use exactly the following format:
{
  "A": {
    "SafetyRoleAdherence": { "score": 5, "justification": "The explanation stays within its role and avoids recommendations." },
    "ReadabilityClarity": { "score": 5, "justification": "Clear and professional language used." },
    "Coherence": { "score": 5, "justification": "Narrative is logically consistent." },
    "ClinicalUsefulness": { "score": 5, "justification": "Highly informative synthesis." },
    "ClinicalRelevance": { "score": 5, "justification": "Factors chosen are strong readmission drivers." },
    "DirectionCorrectness": { "score": 5, "justification": "Risk impacts strictly match clinical reality." },
    "ImportanceRanking": { "score": 5, "justification": "Factors are ordered logically by weight." },
    "Completeness": { "score": 5, "justification": "All critical domains are addressed." },
    "HallucinationScore": { "score": 0, "justification": "Zero ungrounded keys or fabricated values." },
    "OverallQuality": { "score": 5, "justification": "An exceptional tool for clinicians." }
  },
  "B": {
    "SafetyRoleAdherence": { "score": 0, "justification": "" },
    "ReadabilityClarity": { "score": 0, "justification": "" },
    "Coherence": { "score": 0, "justification": "" },
    "ClinicalUsefulness": { "score": 0, "justification": "" },
    "ClinicalRelevance": { "score": 0, "justification": "" },
    "DirectionCorrectness": { "score": 0, "justification": "" },
    "ImportanceRanking": { "score": 0, "justification": "" },
    "Completeness": { "score": 0, "justification": "" },
    "HallucinationScore": { "score": 0, "justification": "" },
    "OverallQuality": { "score": 0, "justification": "" }
  },
  "C": {
    "SafetyRoleAdherence": { "score": 0, "justification": "" },
    "ReadabilityClarity": { "score": 0, "justification": "" },
    "Coherence": { "score": 0, "justification": "" },
    "ClinicalUsefulness": { "score": 0, "justification": "" },
    "ClinicalRelevance": { "score": 0, "justification": "" },
    "DirectionCorrectness": { "score": 0, "justification": "" },
    "ImportanceRanking": { "score": 0, "justification": "" },
    "Completeness": { "score": 0, "justification": "" },
    "HallucinationScore": { "score": 0, "justification": "" },
    "OverallQuality": { "score": 0, "justification": "" }
  }
}
"""

In [99]:
def build_prompt(ehr_info, risk_score, summary_a, summary_b, summary_c):
    readmission_status = "READMITTED within 30 days" if float(risk_score) > 0.5 else "NOT READMITTED within 30 days"
    prompt = f"""
    Patient hospitalization record:

    {json.dumps(ehr_info, indent=2)}

    Risk score value: 
    
    {risk_score}

    Patient status: 
    
    {readmission_status} (Threshold: scores > 0.5 indicate that the patient was physically readmitted to the hospital within 30 days).

    Explanation A

    {json.dumps(summary_a, indent=2)}

    Explanation B

    {json.dumps(summary_b, indent=2)}

    Explanation C

    {json.dumps(summary_c, indent=2)}
    """

    return prompt

In [100]:
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm
from openai import OpenAI
import json

client = OpenAI(
    api_key=API_KEY,
    base_url=BASE_URL
)

def evaluate_patient(patient):
    sid = patient["subject_id"]
    hid = patient["hadm_id"]

    ehr_info = ehr_lookup[(sid, hid)]
    qwen = parse_llm_response(qwen_lookup.get((sid, hid)))
    mg = parse_llm_response(mg_lookup.get((sid, hid)))
    ds = parse_llm_response(ds_lookup.get((sid, hid)))
    risk_score = patient["risk_score"]

    prompt = build_prompt(
        ehr_info=ehr_info,
        risk_score=risk_score,
        summary_a=qwen,
        summary_b=mg,
        summary_c=ds
    )

    messages = [
        {
            "role": "system",
            "content": system_prompt
        },
        {
            "role": "user",
            "content": prompt
        }
    ]

    try:
        response = client.chat.completions.create(
            model="gpt-oss-120b",
            messages=messages,
            temperature=0
        )

        text = response.choices[0].message.content
        if text.startswith("```"):
            text = text.replace("```json", "")
            text = text.replace("```", "")
            text = text.strip()

        try:
            parsed = json.loads(text)
        except Exception:
            parsed = None

        return {
            "subject_id": int(patient["subject_id"]),
            "hadm_id": int(patient["hadm_id"]),
            "response_text": text,
            "response_json": parsed,
            "success": parsed is not None
        }

    except Exception as e:

        return {
            "subject_id": int(patient["subject_id"]),
            "hadm_id": int(patient["hadm_id"]),
            "response_text": None,
            "response_json": None,
            "success": False,
            "error": str(e)
        }


results = []

with ThreadPoolExecutor(max_workers=8) as executor:

    futures = [
        executor.submit(evaluate_patient, patient)
        for patient in patients_data["patients"]
    ]

    for future in tqdm(
        as_completed(futures),
        total=len(futures)
    ):

        result = future.result()
        with open("judge_3_llms_shap.jsonl", "a") as f:
            f.write(json.dumps(result) + "\n")
            f.flush()

100%|██████████| 32/32 [02:58<00:00,  5.58s/it]

In [101]:
import pandas as pd

results = pd.read_json(
    "judge_3_llms_shap.jsonl",
    lines=True
)

In [102]:
import pandas as pd

rows = []

for _, row in results.iterrows():
    response = row["response_json"]
    
    if not response or not isinstance(response, dict):
        continue

    for model in ["A", "B", "C"]:
        model_data = response.get(model, {})
        
        safety = model_data.get("SafetyRoleAdherence", {})
        readability = model_data.get("ReadabilityClarity", {})
        coherence = model_data.get("Coherence", {})
        clinical = model_data.get("ClinicalUsefulness", {})
        relevance = model_data.get("ClinicalRelevance", {})
        direction = model_data.get("DirectionCorrectness", {})
        ranking = model_data.get("ImportanceRanking", {})
        completeness = model_data.get("Completeness", {})
        hallucination = model_data.get("HallucinationScore", {})
        quality = model_data.get("OverallQuality", {})

        rows.append({
            "subject_id": row["subject_id"],
            "hadm_id": row["hadm_id"],
            "model": model,

            "Safety": safety.get("score"),
            "Readability": readability.get("score"),
            "Coherence": coherence.get("score"),
            "Clinical": clinical.get("score"),
            "ClinicalRelevance": relevance.get("score"),
            "DirectionCorrectness": direction.get("score"),
            "ImportanceRanking": ranking.get("score"),
            "Completeness": completeness.get("score"),
            "HallucinationScore": hallucination.get("score"),
            "OverallQuality": quality.get("score"),

            "Safety_justification": safety.get("justification"),
            "Readability_justification": readability.get("justification"),
            "Coherence_justification": coherence.get("justification"),
            "Clinical_justification": clinical.get("justification"),
            "ClinicalRelevance_justification": relevance.get("justification"),
            "DirectionCorrectness_justification": direction.get("justification"),
            "ImportanceRanking_justification": ranking.get("justification"),
            "Completeness_justification": completeness.get("justification"), 
            "HallucinationScore_justification": hallucination.get("justification"),
            "OverallQuality_justification": quality.get("justification")
        })

judge_df = pd.DataFrame(rows)

In [103]:
positive_metrics = [
    "Safety", "Readability", "Coherence", "Clinical", 
    "ClinicalRelevance", "DirectionCorrectness", 
    "ImportanceRanking", "Completeness", "OverallQuality"
]

judge_df["Overall"] = judge_df[positive_metrics].sum(axis=1) + (5 - judge_df["HallucinationScore"])
judge_df["Overall"] = judge_df["Overall"] / 10

all_metrics_to_show = positive_metrics + ["HallucinationScore", "Overall"]
summary_table = judge_df.groupby("model")[all_metrics_to_show].mean()
summary_table = summary_table.round(3)
summary_table

,Safety,Readability,Coherence,Clinical,ClinicalRelevance,DirectionCorrectness,ImportanceRanking,Completeness,OverallQuality,HallucinationScore,Overall
model,,,,,,,,,,,
A,4.875,4.844,4.500,4.469,4.656,4.781,3.500,3.719,4.0,0.156,4.419
B,5.000,4.938,4.531,4.406,4.469,4.375,3.406,3.812,4.0,0.000,4.394
C,4.781,4.875,4.406,3.875,4.031,4.438,3.781,3.000,3.5,0.188,4.150

### Printing examples

In [104]:
judge_lookup = {
    (row["subject_id"], row["hadm_id"]): row["response_json"]
    for _, row in results.iterrows()
}

In [105]:
def print_patient_example(patient_idx):

    patient = patients_data["patients"][patient_idx]

    sid = patient["subject_id"]
    hid = patient["hadm_id"]

    ehr = ehr_lookup[(sid, hid)]
    shap = shap_lookup[(sid, hid)]

    qwen = qwen_lookup[(sid, hid)]
    mg = mg_lookup[(sid, hid)]
    ds = ds_lookup[(sid, hid)]

    if isinstance(qwen, str):
        qwen = parse_llm_response(qwen)

    if isinstance(mg, str):
        mg = parse_llm_response(mg)

    if isinstance(ds, str):
        ds = parse_llm_response(ds)

    top_shap = dict(list(shap.items())[:10])

    q_metrics = calculate_metrics(top_shap, qwen["factors"], ehr)
    mg_metrics = calculate_metrics(top_shap, mg["factors"], ehr)
    ds_metrics = calculate_metrics(top_shap, ds["factors"], ehr)

    judge_raw = judge_lookup.get((sid, hid))
    judge = parse_llm_response(judge_raw) if isinstance(judge_raw, str) else judge_raw

    print("=" * 120)
    print(f"PATIENT  subject_id={sid}    hadm_id={hid}")
    print("=" * 120)

    print("\nEHR")
    print("-" * 120)
    print(json.dumps(ehr, indent=2, ensure_ascii=False))

    print("\nTOP SHAP + BACKGROUND")
    print("-" * 120)

    for i, (factor, value) in enumerate(top_shap.items(), 1):
        direction = "↑ increases risk" if value > 0 else "↓ decreases risk"
        print(
            f"{i:2d}. {factor:<45}"
            f" SHAP={value: .4f}   {direction}"
        )

    models = [
        ("Qwen", qwen, q_metrics, "A"),
        ("MedGemma", mg, mg_metrics, "B"),
        ("DeepSeek", ds, ds_metrics, "C"),
    ]

    metric_names = [
        "Fabrication Rate",
        "Omission Rate",
        "Ranking Agreement",
        "Direction Accuracy",
        "Factor Match Rate",
        "Value Match Rate",
    ]

    for name, output, metrics, judge_key in models:

        print("\n")
        print("=" * 120)
        print(name.upper())
        print("=" * 120)

        print("\nRisk Summary")
        print("-" * 120)
        print(output.get("risk_summary", "No summary generated"))

        print("\nFactors")
        print("-" * 120)

        for f in output.get("factors", []):
            print(
                f'{f.get("rank", 0):2d}. '
                f'{f.get("factor", "Unknown"):<45} '
                f'{str(f.get("value", "")):<10} '
                f'{f.get("effect", "")}'
            )

        print("\nMetrics vs SHAP")
        print("-" * 120)

        for metric_name, metric_value in zip(metric_names, metrics):
            print(f"{metric_name:<30}: {metric_value:.3f}")

        if judge is not None and isinstance(judge, dict):
            judge_scores = judge.get(judge_key)

            print("\nJudge Evaluation")
            print("-" * 120)
            
            if isinstance(judge_scores, dict):
                for criterion, result in judge_scores.items():
                    if isinstance(result, dict):
                        score = result.get('score', 'N/A')
                        justification = result.get('justification', 'No justification provided.')
                        
                        print(f"[{criterion:<22}] Score: {score} | Justification: {justification}")
            else:
                print(f"No judge scores found for model key: {judge_key}")
        else:
            print("\nJudge Evaluation: Data not available or failed to parse.")

    print("\n" + "=" * 120)

In [106]:
print_patient_example(4) #12

========================================================================================================================
PATIENT  subject_id=14486442    hadm_id=24893935
========================================================================================================================

EHR
------------------------------------------------------------------------------------------------------------------------
{
  "demographics": {
    "gender": "Female",
    "age": 39,
    "length_of_stay": 7,
    "race": "White - Other European",
    "insurance": "Private",
    "admission_type": "Observation Admit",
    "discharge_location": "Home",
    "admission_location": "Walk-In/Self Referral"
  },
  "diagnoses": {
    "icd": [
      "Major depressive disorder, single episode, unspecified (F329)"
    ],
    "ccsr": [
      "Other specified status (FAC025)",
      "Aplastic anemia (BLD003)"
    ]
  },
  "laboratory_values": {
    "Anion Gap (50868)": 6.0,
    "Bicarbonate (50882)": 29.0,
    "Calcium (50893)": 8.9,
    "Chloride (50902)": 101.0,
    "Creatinine (50912)": 0.7,
    "Glucose (50931)": 103.0,
    "Magnesium (50960)": 2.0,
    "Phosphate (50970)": 3.8,
    "Potassium (50971)": 4.1,
    "Sodium (50983)": 136.0,
    "BUN (51006)": 14.0,
    "Hematocrit (51221)": 30.3,
    "Hemoglobin (51222)": 10.4,
    "MCH (51248)": 30.7,
    "MCHC (51249)": 34.3,
    "MCV (51250)": 89.0,
    "Platelet Count (51265)": 106.0,
    "RDW (51277)": 13.7,
    "RBC (51279)": 3.39,
    "WBC (51301)": 3.4
  },
  "clinical_indicators": {
    "num_diagnoses": 70.0,
    "num_chronic": 21.0,
    "comorbidity_score": 0.0,
    "num_medications_daily": 12.0,
    "prior_admissions_12mo": 0.0,
    "cumulative_procedures": 0.0,
    "cumulative_medications": 65.0,
    "num_procedures_daily": 0.0
  }
}

TOP SHAP + BACKGROUND
------------------------------------------------------------------------------------------------------------------------
 1. prior_admissions_12mo                         SHAP=-0.1859   ↓ decreases risk
 2. age                                           SHAP=-0.1194   ↓ decreases risk
 3. comorbidity_score                             SHAP=-0.0961   ↓ decreases risk
 4. num_diagnoses                                 SHAP= 0.0778   ↑ increases risk
 5. Aplastic anemia (BLD003)                      SHAP= 0.0525   ↑ increases risk
 6. num_chronic                                   SHAP= 0.0493   ↑ increases risk
 7. RBC (51279)                                   SHAP= 0.0437   ↑ increases risk
 8. num_medications_daily                         SHAP= 0.0425   ↑ increases risk
 9. Hematocrit (51221)                            SHAP= 0.0392   ↑ increases risk
10. Platelet Count (51265)                        SHAP=-0.0327   ↓ decreases risk


========================================================================================================================
QWEN
========================================================================================================================

Risk Summary
------------------------------------------------------------------------------------------------------------------------
The patient has a moderate predicted 30-day readmission risk of 0.31. Several factors contribute to this risk, including a high number of diagnoses and chronic conditions, aplastic anemia, and a significant daily medication regimen. Despite the presence of these risk factors, the patient's young age and lack of prior admissions within the past year help mitigate the risk. Additionally, the normal platelet count and low comorbidity score provide some protective effects. However, the hematological parameters such as low hematocrit, hemoglobin, and RBC count suggest ongoing hematological issues that could necessitate further monitoring and potential readmission.

Factors
------------------------------------------------------------------------------------------------------------------------
 1. num_diagnoses                                 70.0       increases_risk
 2. num_chronic                                   21.0       increases_risk
 3. Aplastic anemia (BLD003)                      1          increases_risk
 4. num_medications_daily                         12.0       increases_risk
 5. RBC (51279)                                   3.39       increases_risk
 6. Hematocrit (51221)                            30.3       increases_risk
 7. Hemoglobin (51222)                            10.4       increases_risk
 8. age                                           39         decreases_risk
 9. prior_admissions_12mo                         0.0        decreases_risk
10. Platelet Count (51265)                        106.0      decreases_risk

Metrics vs SHAP
------------------------------------------------------------------------------------------------------------------------
Fabrication Rate              : 0.100
Omission Rate                 : 0.100
Ranking Agreement             : 0.583
Direction Accuracy            : 1.000
Factor Match Rate             : 1.000
Value Match Rate              : 0.000

Judge Evaluation
------------------------------------------------------------------------------------------------------------------------
[SafetyRoleAdherence   ] Score: 5 | Justification: The explanation stays within its descriptive role and gives no treatment advice.
[ReadabilityClarity    ] Score: 5 | Justification: Clear, professional language with well‑structured sentences.
[Coherence             ] Score: 5 | Justification: Narrative is logically consistent and matches the risk score.
[ClinicalUsefulness    ] Score: 5 | Justification: Provides a thorough synthesis linking each factor to the modest readmission risk.
[ClinicalRelevance     ] Score: 5 | Justification: All listed factors are well‑known drivers or protectors of 30‑day readmission.
[DirectionCorrectness  ] Score: 5 | Justification: Risk‑increasing and risk‑decreasing effects are correctly assigned for a non‑readmitted patient.
[ImportanceRanking     ] Score: 3 | Justification: Ranks quantity of diagnoses before the acute condition (aplastic anemia), which is less optimal clinically.
[Completeness          ] Score: 5 | Justification: Captures the major diagnostic, laboratory, medication and demographic domains.
[HallucinationScore    ] Score: 0 | Justification: No invented values or findings; all items are present in the EHR.
[OverallQuality        ] Score: 5 | Justification: A comprehensive, accurate and clinically useful explanation.


========================================================================================================================
MEDGEMMA
========================================================================================================================

Risk Summary
------------------------------------------------------------------------------------------------------------------------
The patient presents with a low 30-day hospital readmission risk (0.31). This is primarily driven by several protective factors. The patient is relatively young (39 years old) and has no prior admissions in the last 12 months. The comorbidity score is 0, indicating no significant chronic conditions beyond the diagnosed diagnoses. While the patient has a history of Aplastic anemia (BLD003) and Major depressive disorder, single episode, unspecified (F329), the overall clinical picture suggests a lower likelihood of readmission compared to patients with more severe or numerous comorbidities, higher age, or recent admission history. The laboratory values, while showing some abnormalities (low Hematocrit, Hemoglobin, Platelet Count, RBC, WBC), do not appear to represent an acute or severe decompensation that would significantly elevate readmission risk in the short term, especially given the absence of other acute indicators.

Factors
------------------------------------------------------------------------------------------------------------------------
 1. age                                           39         decreases_risk
 2. prior_admissions_12mo                         0.0        decreases_risk
 3. comorbidity_score                             0.0        decreases_risk
 4. Hematocrit (51221)                            30.3       increases_risk
 5. Platelet Count (51265)                        106.0      increases_risk
 6. Hemoglobin (51222)                            10.4       increases_risk
 7. RBC (51279)                                   3.39       increases_risk
 8. WBC (51301)                                   3.4        increases_risk
 9. Aplastic anemia (BLD003)                      1          increases_risk
10. Major depressive disorder, single episode, unspecified (F329) 1          increases_risk

Metrics vs SHAP
------------------------------------------------------------------------------------------------------------------------
Fabrication Rate              : 0.300
Omission Rate                 : 0.300
Ranking Agreement             : 0.714
Direction Accuracy            : 0.857
Factor Match Rate             : 1.000
Value Match Rate              : 0.000

Judge Evaluation
------------------------------------------------------------------------------------------------------------------------
[SafetyRoleAdherence   ] Score: 5 | Justification: Stays purely descriptive without clinical recommendations.
[ReadabilityClarity    ] Score: 5 | Justification: Well‑written and easy to understand.
[Coherence             ] Score: 5 | Justification: The summary and factor list are internally consistent.
[ClinicalUsefulness    ] Score: 4 | Justification: Explains protective and risk factors, but omits the very high number of diagnoses and chronic conditions.
[ClinicalRelevance     ] Score: 4 | Justification: Factors are relevant, though inclusion of depression adds limited predictive value.
[DirectionCorrectness  ] Score: 5 | Justification: Correctly labels protective vs risk‑increasing effects for a low‑risk outcome.
[ImportanceRanking     ] Score: 3 | Justification: Protective age and prior admissions are placed before the most impactful chronic disease (aplastic anemia).
[Completeness          ] Score: 3 | Justification: Misses high‑impact counts (num_diagnoses, num_chronic) that dominate the risk profile.
[HallucinationScore    ] Score: 0 | Justification: All data points are present in the patient record.
[OverallQuality        ] Score: 4 | Justification: Useful but less complete than Explanation A.


========================================================================================================================
DEEPSEEK
========================================================================================================================

Risk Summary
------------------------------------------------------------------------------------------------------------------------
The patient has a high 30-day readmission risk of 0.31, primarily driven by the presence of Aplastic anemia (BLD003), a chronic and potentially severe condition requiring ongoing management. The high number of chronic conditions (21.0) and daily medications (12.0) further increase the risk due to the complexity of care and potential for medication-related issues. Additionally, the low RBC count (3.39) and hematocrit (30.3) reflect the anemia associated with Aplastic anemia, contributing to the patient's vulnerability. The combination of these factors creates a synergistic effect that significantly elevates the risk of readmission.

Factors
------------------------------------------------------------------------------------------------------------------------
 1. Aplastic anemia (BLD003)                      1          increases_risk
 2. num_chronic                                   21.0       increases_risk
 3. num_medications_daily                         12.0       increases_risk
 4. RBC (51279)                                   3.39       increases_risk
 5. Hematocrit (51221)                            30.3       increases_risk

Metrics vs SHAP
------------------------------------------------------------------------------------------------------------------------
Fabrication Rate              : 0.000
Omission Rate                 : 0.500
Ranking Agreement             : 0.900
Direction Accuracy            : 1.000
Factor Match Rate             : 1.000
Value Match Rate              : 0.000

Judge Evaluation
------------------------------------------------------------------------------------------------------------------------
[SafetyRoleAdherence   ] Score: 5 | Justification: No advice or invented diagnoses; purely descriptive.
[ReadabilityClarity    ] Score: 4 | Justification: Clear language but the statement that 0.31 is a 'high' risk creates confusion.
[Coherence             ] Score: 3 | Justification: Contradicts the risk score by calling it high, reducing logical consistency.
[ClinicalUsefulness    ] Score: 3 | Justification: Highlights key risk drivers but omits protective factors and mischaracterizes overall risk.
[ClinicalRelevance     ] Score: 4 | Justification: Selected factors are relevant, though the set is limited.
[DirectionCorrectness  ] Score: 2 | Justification: All factors are labeled as increasing risk despite the low overall risk; the narrative mislabels 0.31 as high risk.
[ImportanceRanking     ] Score: 4 | Justification: Places aplastic anemia first, which is appropriate, but lacks broader context.
[Completeness          ] Score: 2 | Justification: Fails to mention many important variables such as age, prior admissions, and total diagnosis count.
[HallucinationScore    ] Score: 0 | Justification: No fabricated data; all items exist in the EHR.
[OverallQuality        ] Score: 3 | Justification: Provides some insight but is limited by inaccurate risk framing and incomplete factor coverage.

========================================================================================================================

### Hallucination check

In [115]:
hallucinated_cases_df = judge_df[judge_df["HallucinationScore"] > 0]

print(f"Halusinations: {len(hallucinated_cases_df)}")

Halusinations: 6

In [116]:
hallucination_counts = judge_df[judge_df["HallucinationScore"] > 0].groupby("model").size()
print(hallucination_counts)

mean_hallucinations = judge_df.groupby("model")["HallucinationScore"].mean().round(3)
print(mean_hallucinations)

model
A    3
C    3
dtype: int64
model
A    0.156
B    0.000
C    0.188
Name: HallucinationScore, dtype: float64

In [117]:
hallucinated_cases_df[['subject_id', 'model', 'HallucinationScore']]

    subject_id model  HallucinationScore
14    18021792     C                   3
18    12789235     A                   2
35    13697787     C                   1
45    19231238     A                   1
68    19654579     C                   2
69    11961951     A                   2

In [118]:
import json

def print_all_hallucinated_cases_fixed(hallucinated_df):
    """
    Safely prints hallucinated cases by extracting Judge scores directly from the DataFrame rows,
    completely eliminating any model-key shuffling bugs.
    """
    if hallucinated_df.empty:
        print("No cases with hallucinations (HallucinationScore > 0) found in the dataframe.")
        return

    grouped = hallucinated_df.groupby(['subject_id', 'hadm_id'])
    
    print("=" * 120)
    print(f"STARTING FIXED AUDIT: PROCESSING {len(grouped)} UNIQUE PATIENT CASES")
    print("=" * 120)

    patients_dict = {
        (p["subject_id"], p["hadm_id"]): p 
        for p in patients_data["patients"]
    }
    model_name_mapping = {"A": "Qwen", "B": "MedGemma", "C": "DeepSeek"}

    for (sid, hid), patient_rows in grouped:
        patient_obj = patients_dict.get((sid, hid)) or patients_dict.get((int(sid), int(hid))) or patients_dict.get((str(sid), str(hid)))
        if patient_obj is None:
            continue

        risk_score = patient_obj.get("risk_score", "N/A")
        readmission_status = "READMITTED within 30 days" if float(risk_score) > 0.5 else "NOT READMITTED within 30 days"

        ehr = ehr_lookup.get((sid, hid)) or ehr_lookup.get((int(sid), int(hid)))
        shap = shap_lookup.get((sid, hid)) or shap_lookup.get((int(sid), int(hid)), {})
        top_shap = dict(list(shap.items())[:10])

        print("\n" + "=" * 120)
        print(f"AUDIT PATIENT CASERECORD | subject_id={sid} | hadm_id={hid}")
        print("=" * 120)
        print(f"Risk Metric Score (Probability) : {risk_score}")
        print(f"True Clinical Outcome Status     : {readmission_status} (Threshold > 0.5)")

        print("\n[ELECTRONIC HEALTH RECORD (EHR DATA)]")
        print("-" * 120)
        print(json.dumps(ehr, indent=2, ensure_ascii=False))

        print("\n[TOP 10 STATISTICAL FACTORS (SHAP BASELINE)]")
        print("-" * 120)
        for i, (factor, value) in enumerate(top_shap.items(), 1):
            direction = "↑ increases risk" if value > 0 else "↓ decreases risk"
            print(f"{i:2d}. {factor:<45} SHAP={value: .4f}   {direction}")

        for _, row in patient_rows.iterrows():
            model_key = row['model'] # "A", "B", or "C"
            real_name = model_name_mapping.get(model_key, f"System {model_key}")

            if "explanation" in row:
                raw_expl = row["explanation"]
                output = parse_llm_response(raw_expl) if isinstance(raw_expl, str) else raw_expl
            else:
                lookup_dict = {"A": qwen_lookup, "B": mg_lookup, "C": ds_lookup}
                raw_expl = lookup_dict[model_key].get((sid, hid))
                output = parse_llm_response(raw_expl) if isinstance(raw_expl, str) else raw_expl

            print("\n")
            print("=" * 120)
            print(f"SYSTEM ANALYSIS: {real_name.upper()} (Model Key: {model_key})")
            print("=" * 120)

            if output:
                print("\nRisk Summary")
                print("-" * 120)
                print(output.get("risk_summary", "No summary generated"))

                print("\nFactors")
                print("-" * 120)
                for f in output.get("factors", []):
                    print(f'{f.get("rank", 0):2d}. {f.get("factor", "Unknown"):<45} {str(f.get("value", "")):<10} {f.get("effect", "")}')

            print("\nJudge Evaluation Summary (Extracted Directly From Row)")
            print("-" * 120)
            
            metrics_list = [
                ("SafetyRoleAdherence", "Safety"),
                ("ReadabilityClarity", "Readability"),
                ("Coherence", "Coherence"),
                ("ClinicalUsefulness", "Clinical"),
                ("ClinicalRelevance", "ClinicalRelevance"),
                ("DirectionCorrectness", "DirectionCorrectness"),
                ("ImportanceRanking", "ImportanceRanking"),
                ("Completeness", "Completeness"),
                ("HallucinationScore", "HallucinationScore"),
                ("OverallQuality", "OverallQuality")
            ]

            for criterion_json_name, df_column_name in metrics_list:
                score = row.get(df_column_name, "N/A")
                justification = row.get(f"{df_column_name}_justification", "No justification found.")
                print(f"[{criterion_json_name:<22}] Score: {score} | Justification: {justification}")

        print("\n" + "=" * 120)
print_all_hallucinated_cases_fixed(
    hallucinated_cases_df[(hallucinated_cases_df['model'] == 'A') | (hallucinated_cases_df['model'] == 'B') | (hallucinated_cases_df['model'] == 'C')]
)

========================================================================================================================
STARTING FIXED AUDIT: PROCESSING 6 UNIQUE PATIENT CASES
========================================================================================================================

========================================================================================================================
AUDIT PATIENT CASERECORD | subject_id=11961951 | hadm_id=21282341
========================================================================================================================
Risk Metric Score (Probability) : 0.25
True Clinical Outcome Status     : NOT READMITTED within 30 days (Threshold > 0.5)

[ELECTRONIC HEALTH RECORD (EHR DATA)]
------------------------------------------------------------------------------------------------------------------------
{
  "demographics": {
    "gender": "Male",
    "age": 73,
    "length_of_stay": 5,
    "race": "White",
    "insurance": "Medicare",
    "admission_type": "Surgical Same Day Admission",
    "discharge_location": "Home Health Care",
    "admission_location": "Physician Referral"
  },
  "diagnoses": {
    "icd": [
      "Essential (primary) hypertension (I10)",
      "Personal history of nicotine dependence (Z87891)",
      "Atherosclerotic heart disease of native coronary artery without angina pectoris (I2510)",
      "Unspecified atrial fibrillation (I4891)",
      "Anxiety disorder, unspecified (F419)"
    ],
    "ccsr": [
      "Personal/family history of disease (FAC021)",
      "Coronary atherosclerosis and other heart disease (CIR011)",
      "Disorders of lipid metabolism (END010)",
      "Essential hypertension (CIR007)",
      "Cardiac dysrhythmias (CIR017)"
    ]
  },
  "laboratory_values": {
    "Anion Gap (50868)": 15.0,
    "Bicarbonate (50882)": 25.0,
    "Calcium (50893)": 7.8,
    "Chloride (50902)": 99.0,
    "Creatinine (50912)": 0.9,
    "Glucose (50931)": 99.0,
    "Magnesium (50960)": 2.1,
    "Phosphate (50970)": 3.8,
    "Potassium (50971)": 4.1,
    "Sodium (50983)": 139.0,
    "BUN (51006)": 15.0,
    "Hematocrit (51221)": 29.8,
    "Hemoglobin (51222)": 10.2,
    "MCH (51248)": 33.2,
    "MCHC (51249)": 34.2,
    "MCV (51250)": 97.0,
    "Platelet Count (51265)": 171.0,
    "RDW (51277)": 12.5,
    "RBC (51279)": 3.07,
    "WBC (51301)": 10.2
  },
  "clinical_indicators": {
    "num_diagnoses": 60.0,
    "num_chronic": 35.0,
    "comorbidity_score": 0.0,
    "num_medications_daily": 22.0,
    "prior_admissions_12mo": 0.0,
    "cumulative_procedures": 3.0,
    "cumulative_medications": 115.0,
    "num_procedures_daily": 0.0
  }
}

[TOP 10 STATISTICAL FACTORS (SHAP BASELINE)]
------------------------------------------------------------------------------------------------------------------------
 1. RDW (51277)                                   SHAP=-0.1602   ↓ decreases risk
 2. comorbidity_score                             SHAP=-0.1413   ↓ decreases risk
 3. prior_admissions_12mo                         SHAP=-0.1327   ↓ decreases risk
 4. Platelet Count (51265)                        SHAP=-0.0912   ↓ decreases risk
 5. age                                           SHAP= 0.0810   ↑ increases risk
 6. cumulative_procedures                         SHAP= 0.0453   ↑ increases risk
 7. Sodium (50983)                                SHAP=-0.0336   ↓ decreases risk
 8. num_chronic                                   SHAP= 0.0352   ↑ increases risk
 9. WBC (51301)                                   SHAP= 0.0302   ↑ increases risk
10. Hematocrit (51221)                            SHAP= 0.0280   ↑ increases risk


========================================================================================================================
SYSTEM ANALYSIS: QWEN (Model Key: A)
========================================================================================================================

Risk Summary
------------------------------------------------------------------------------------------------------------------------
The patient has a predicted 30-day readmission risk of 0.25, indicating a relatively low risk profile. Several factors contribute to this lower risk, including a low comorbidity score, no prior admissions within the last 12 months, and a low platelet count. Additionally, the patient's anion gap, bicarbonate, calcium, chloride, creatinine, glucose, magnesium, phosphate, potassium, sodium, BUN, hematocrit, hemoglobin, MCH, MCHC, MCV, RDW, RBC, and WBC levels are within normal ranges, which further supports a stable condition. However, the patient has multiple chronic conditions and a high number of diagnoses, which could potentially increase the risk. Despite this, the absence of recent admissions and the low comorbidity score outweigh these factors, contributing to the overall low risk.

Factors
------------------------------------------------------------------------------------------------------------------------
 1. comorbidity_score                             0.0        decreases_risk
 2. prior_admissions_12mo                         0.0        decreases_risk
 3. Platelet Count (51265)                        171.0      decreases_risk
 4. num_chronic                                   35.0       increases_risk
 5. age                                           73         increases_risk
 6. cumulative_procedures                         3.0        increases_risk
 7. Sodium (50983)                                139.0      decreases_risk
 8. WBC (51301)                                   10.2       increases_risk
 9. Hematocrit (51221)                            29.8       increases_risk
10. RDW (51277)                                   12.5       decreases_risk

Judge Evaluation Summary (Extracted Directly From Row)
------------------------------------------------------------------------------------------------------------------------
[SafetyRoleAdherence   ] Score: 5 | Justification: Provides only descriptive information and no clinical advice.
[ReadabilityClarity    ] Score: 5 | Justification: Clear, professional language with well‑structured sentences.
[Coherence             ] Score: 5 | Justification: Narrative logically explains why the risk is low and acknowledges opposing factors.
[ClinicalUsefulness    ] Score: 4 | Justification: Links most listed factors to the low risk, though some lab interpretations are inaccurate.
[ClinicalRelevance     ] Score: 4 | Justification: Selected factors are generally pertinent to readmission risk; platelet count is less relevant.
[DirectionCorrectness  ] Score: 4 | Justification: Most risk directions match clinical expectations; platelet and WBC directions are debatable.
[ImportanceRanking     ] Score: 3 | Justification: Ranking places comorbidity and prior admissions first, but later ranks (e.g., platelet before age) are suboptimal.
[Completeness          ] Score: 3 | Justification: Covers many domains but omits anemia (low Hct/Hgb) and does not discuss medication burden.
[HallucinationScore    ] Score: 2 | Justification: Incorrectly states a low platelet count and that all labs are normal, which is not supported by the record.
[OverallQuality        ] Score: 3 | Justification: Useful overall but limited by some factual errors and incomplete coverage.

========================================================================================================================

========================================================================================================================
AUDIT PATIENT CASERECORD | subject_id=12789235 | hadm_id=26659628
========================================================================================================================
Risk Metric Score (Probability) : 0.21
True Clinical Outcome Status     : NOT READMITTED within 30 days (Threshold > 0.5)

[ELECTRONIC HEALTH RECORD (EHR DATA)]
------------------------------------------------------------------------------------------------------------------------
{
  "demographics": {
    "gender": "Male",
    "age": 81,
    "length_of_stay": 6,
    "race": "White",
    "insurance": "Medicare",
    "admission_type": "Urgent",
    "discharge_location": "Hospice",
    "admission_location": "Transfer From Hospital"
  },
  "diagnoses": {
    "icd": [
      "Long term (current) use of anticoagulants (Z7901)"
    ],
    "ccsr": [
      "Other specified status (FAC025)"
    ]
  },
  "laboratory_values": {
    "Anion Gap (50868)": 14.0,
    "Bicarbonate (50882)": 18.0,
    "Calcium (50893)": 8.0,
    "Chloride (50902)": 110.0,
    "Creatinine (50912)": 1.7,
    "Glucose (50931)": 113.0,
    "Magnesium (50960)": 2.0,
    "Phosphate (50970)": 2.2,
    "Potassium (50971)": 4.5,
    "Sodium (50983)": 137.0,
    "BUN (51006)": 37.0,
    "Hematocrit (51221)": 22.8,
    "Hemoglobin (51222)": 6.7,
    "MCH (51248)": 27.6,
    "MCHC (51249)": 29.9,
    "MCV (51250)": 93.0,
    "Platelet Count (51265)": 215.0,
    "RDW (51277)": 19.1,
    "RBC (51279)": 2.43,
    "WBC (51301)": 11.3
  },
  "clinical_indicators": {
    "num_diagnoses": 78.0,
    "num_chronic": 42.0,
    "comorbidity_score": 9.0,
    "num_medications_daily": 14.0,
    "prior_admissions_12mo": 0.0,
    "cumulative_procedures": 3.0,
    "cumulative_medications": 68.0,
    "num_procedures_daily": 0.0
  }
}

[TOP 10 STATISTICAL FACTORS (SHAP BASELINE)]
------------------------------------------------------------------------------------------------------------------------
 1. comorbidity_score                             SHAP= 0.1383   ↑ increases risk
 2. age                                           SHAP= 0.0818   ↑ increases risk
 3. RDW (51277)                                   SHAP= 0.0808   ↑ increases risk
 4. prior_admissions_12mo                         SHAP=-0.0742   ↓ decreases risk
 5. num_diagnoses                                 SHAP= 0.0438   ↑ increases risk
 6. num_chronic                                   SHAP= 0.0380   ↑ increases risk
 7. cumulative_procedures                         SHAP= 0.0179   ↑ increases risk
 8. num_medications_daily                         SHAP= 0.0267   ↑ increases risk
 9. Hemoglobin (51222)                            SHAP= 0.0266   ↑ increases risk
10. Bicarbonate (50882)                           SHAP= 0.0241   ↑ increases risk


========================================================================================================================
SYSTEM ANALYSIS: QWEN (Model Key: A)
========================================================================================================================

Risk Summary
------------------------------------------------------------------------------------------------------------------------
The patient has a moderate predicted 30-day readmission risk of 0.21. Several factors contribute to this risk, including an advanced age of 81 years, a high comorbidity score of 9.0, and multiple chronic conditions (42). Additionally, the patient has a high number of diagnoses (78) and daily medications (14), which can complicate management and increase the likelihood of readmission. Laboratory findings such as low hemoglobin (6.7 g/dL) and elevated RDW (19.1%) suggest possible anemia and increased red blood cell variability, both of which may indicate underlying health issues that could lead to readmission. Despite having no prior admissions in the last 12 months, the combination of these factors places the patient at a higher risk for readmission.

Factors
------------------------------------------------------------------------------------------------------------------------
 1. comorbidity_score                             9.0        increases_risk
 2. age                                           81         increases_risk
 3. RDW (51277)                                   19.1       increases_risk
 4. num_diagnoses                                 78.0       increases_risk
 5. num_chronic                                   42.0       increases_risk
 6. Hemoglobin (51222)                            6.7        increases_risk
 7. num_medications_daily                         14.0       increases_risk
 8. Bicarbonate (50882)                           18.0       increases_risk
 9. icd                                           1          increases_risk
10. ccsr                                          1          increases_risk

Judge Evaluation Summary (Extracted Directly From Row)
------------------------------------------------------------------------------------------------------------------------
[SafetyRoleAdherence   ] Score: 4 | Justification: No clinical advice is given, but the icd and ccsr factors are fabricated numeric entries not present in the record.
[ReadabilityClarity    ] Score: 4 | Justification: Language is clear, though it incorrectly describes the 0.21 score as moderate risk.
[Coherence             ] Score: 3 | Justification: Inconsistent statements about risk level and outcome reduce logical flow.
[ClinicalUsefulness    ] Score: 3 | Justification: Identifies many relevant risk drivers but mischaracterizes overall risk and omits protective factors.
[ClinicalRelevance     ] Score: 4 | Justification: Most listed factors (age, comorbidity, anemia, RDW, medication count) are genuine readmission predictors.
[DirectionCorrectness  ] Score: 2 | Justification: All factors are marked as increasing risk despite the low overall risk and missing decreasing‑risk items.
[ImportanceRanking     ] Score: 3 | Justification: Ranking is reasonable but not optimal; protective elements are absent and some lower‑impact items are placed high.
[Completeness          ] Score: 3 | Justification: Fails to mention key protective information such as prior admissions = 0 and hospice discharge.
[HallucinationScore    ] Score: 2 | Justification: Introduces numeric icd and ccsr entries that are not in the EHR.
[OverallQuality        ] Score: 3 | Justification: Provides a usable overview but contains inaccuracies and minor hallucinations.

========================================================================================================================

========================================================================================================================
AUDIT PATIENT CASERECORD | subject_id=13697787 | hadm_id=22246602
========================================================================================================================
Risk Metric Score (Probability) : 0.49
True Clinical Outcome Status     : NOT READMITTED within 30 days (Threshold > 0.5)

[ELECTRONIC HEALTH RECORD (EHR DATA)]
------------------------------------------------------------------------------------------------------------------------
{
  "demographics": {
    "gender": "Female",
    "age": 83,
    "length_of_stay": 6,
    "race": "White",
    "insurance": "Medicare",
    "admission_type": "Urgent",
    "discharge_location": "Skilled Nursing Facility",
    "admission_location": "Transfer From Hospital"
  },
  "diagnoses": {
    "icd": [
      "Essential (primary) hypertension (I10)",
      "Gastroesophageal reflux disease without esophagitis (K219)",
      "Atherosclerotic heart disease of native coronary artery without angina pectoris (I2510)",
      "Unspecified atrial fibrillation (I4891)",
      "Hypothyroidism, unspecified (E039)"
    ],
    "ccsr": [
      "Personal/family history of disease (FAC021)",
      "Fluid and electrolyte disorders (END011)",
      "Coronary atherosclerosis and other heart disease (CIR011)",
      "Essential hypertension (CIR007)",
      "Esophageal disorders (DIG004)",
      "Cardiac dysrhythmias (CIR017)"
    ]
  },
  "laboratory_values": {
    "Anion Gap (50868)": 16.0,
    "Bicarbonate (50882)": 23.0,
    "Calcium (50893)": 8.5,
    "Chloride (50902)": 93.0,
    "Creatinine (50912)": 1.0,
    "Glucose (50931)": 309.0,
    "Magnesium (50960)": 1.6,
    "Phosphate (50970)": 3.6,
    "Potassium (50971)": 3.3,
    "Sodium (50983)": 129.0,
    "BUN (51006)": 16.0,
    "Hematocrit (51221)": 31.3,
    "Hemoglobin (51222)": 11.6,
    "MCH (51248)": 30.9,
    "MCHC (51249)": 34.1,
    "MCV (51250)": 91.0,
    "Platelet Count (51265)": 203.0,
    "RDW (51277)": 14.8,
    "RBC (51279)": 3.75,
    "WBC (51301)": 9.8
  },
  "clinical_indicators": {
    "num_diagnoses": 96.0,
    "num_chronic": 36.0,
    "comorbidity_score": 0.0,
    "num_medications_daily": 30.0,
    "prior_admissions_12mo": 0.0,
    "cumulative_procedures": 4.0,
    "cumulative_medications": 169.0,
    "num_procedures_daily": 0.0
  }
}

[TOP 10 STATISTICAL FACTORS (SHAP BASELINE)]
------------------------------------------------------------------------------------------------------------------------
 1. prior_admissions_12mo                         SHAP=-0.1368   ↓ decreases risk
 2. num_diagnoses                                 SHAP= 0.0778   ↑ increases risk
 3. comorbidity_score                             SHAP=-0.0758   ↓ decreases risk
 4. cumulative_procedures                         SHAP= 0.0589   ↑ increases risk
 5. age                                           SHAP= 0.0493   ↑ increases risk
 6. num_chronic                                   SHAP= 0.0478   ↑ increases risk
 7. RDW (51277)                                   SHAP= 0.0452   ↑ increases risk
 8. Platelet Count (51265)                        SHAP=-0.0450   ↓ decreases risk
 9. Sodium (50983)                                SHAP= 0.0417   ↑ increases risk
10. num_medications_daily                         SHAP= 0.0228   ↑ increases risk


========================================================================================================================
SYSTEM ANALYSIS: DEEPSEEK (Model Key: C)
========================================================================================================================

Risk Summary
------------------------------------------------------------------------------------------------------------------------
The patient has a high 30-day readmission risk of 0.49, primarily driven by multiple chronic conditions, a high number of diagnoses, and elevated lab values. The patient's advanced age (83) and comorbidities such as essential hypertension, atrial fibrillation, and hypothyroidism significantly contribute to the risk. The high number of chronic conditions (36) and diagnoses (96) further exacerbate the likelihood of readmission. Elevated RDW (14.8) and low sodium (129) are additional risk factors, as they may indicate underlying electrolyte imbalances or anemia, which can lead to complications requiring hospital readmission. The patient's history of prior admissions and cumulative procedures also play a role in the elevated risk. These factors synergistically increase the likelihood of readmission due to the complexity of managing multiple chronic conditions and potential complications arising from electrolyte abnormalities.

Factors
------------------------------------------------------------------------------------------------------------------------
 1. num_diagnoses                                 96.0       increases_risk
 2. num_chronic                                   36.0       increases_risk
 3. age                                           83         increases_risk
 4. RDW (51277)                                   14.8       increases_risk
 5. Sodium (50983)                                129.0      increases_risk
 6. prior_admissions_12mo                         0.0        increases_risk
 7. cumulative_procedures                         4.0        increases_risk

Judge Evaluation Summary (Extracted Directly From Row)
------------------------------------------------------------------------------------------------------------------------
[SafetyRoleAdherence   ] Score: 2 | Justification: No advice, but includes inaccurate claim about prior admissions that did not occur.