In [70]:
import pandas as pd
total_deltas = pd.read_csv('total_deltas.csv')
shap_matrix = pd.read_csv('shap_matrix.csv')
prediction_results = pd.read_csv('prediction_results_by_hadm.csv')

total_data_full = pd.read_parquet('ind_hosp.parquet')
correct_predictions = prediction_results[prediction_results['correct_prediction'] == True]
test_pairs = correct_predictions[['subject_id', 'hadm_id']].drop_duplicates()
test_pairs_tuple = list(zip(test_pairs['subject_id'], test_pairs['hadm_id']))

total_data = total_data_full[
    total_data_full[['subject_id', 'hadm_id']].apply(tuple, axis=1).isin(test_pairs_tuple)
].copy()

print(f"Data filtered to test hospitalizations only:")
print(f"  Total rows: {len(total_data)}")
print(f"  Unique patients: {total_data['subject_id'].nunique()}")
print(f"  Unique hospitalizations: {total_data['hadm_id'].nunique()}")

Data filtered to test hospitalizations only:
  Total rows: 237684
  Unique patients: 33311
  Unique hospitalizations: 58385

In [71]:
agg_dict = {}

for col in total_data.columns:
    if col in ['subject_id', 'hadm_id']:
        continue
    
    if col.startswith('icd_'):
        agg_dict[col] = 'max'
    
    elif col.startswith('ccsr_'):
        agg_dict[col] = 'max'
    
    elif col.startswith('lab_') and col.endswith('_daily'):
        agg_dict[col] = 'mean'
    
    elif col in ['cumulative_procedures', 'cumulative_medications']:
        agg_dict[col] = 'mean'
    
    elif col in ['num_medications_daily', 'num_procedures_daily']:
        agg_dict[col] = 'mean'
    
    elif col in ['gender_male', 'age', 'los', 'num_diagnoses', 'num_chronic', 
                 'comorbidity_score', 'prior_admissions_12mo', 
                 'admission_type', 'discharge_location', 'insurance', 'race',
                 'admission_location']:
        agg_dict[col] = 'first'
    
    elif col == 'target_readmission_30d':
        agg_dict[col] = 'max'
    
    else:
        agg_dict[col] = 'first'

print(f"Aggregating {len(agg_dict)} columns...")
total_data = total_data.groupby(['subject_id', 'hadm_id']).agg(agg_dict).reset_index()
total_data.head(5)

Aggregating 136 columns...

,subject_id,hadm_id,dischtime,los,age,day,current_date,num_diagnoses,num_chronic,ccsr_FAC021,...,admission_location_EMERGENCY ROOM,admission_location_INFORMATION NOT AVAILABLE,admission_location_INTERNAL TRANSFER TO OR FROM PSYCH,admission_location_PACU,admission_location_PHYSICIAN REFERRAL,admission_location_PROCEDURE SITE,admission_location_TRANSFER FROM HOSPITAL,admission_location_TRANSFER FROM SKILLED NURSING FACILITY,admission_location_WALK-IN/SELF REFERRAL,gender_male
0,10000764,27897940,2132-10-19,4,86,1,2132-10-14,76,32,1,...,False,False,False,False,False,False,True,False,False,1
1,10001492,27463908,2136-09-25,1,71,1,2136-09-23,4,4,0,...,True,False,False,False,False,False,False,False,False,0
2,10001667,22672901,2173-08-24,1,86,1,2173-08-22,13,6,1,...,False,False,False,False,False,False,True,False,False,0
3,10001725,25563031,2110-04-14,2,46,1,2110-04-11,36,18,1,...,False,False,False,True,False,False,False,False,False,0
4,10001860,21441082,2188-03-30,3,84,1,2188-03-27,36,9,1,...,True,False,False,False,False,False,False,False,False,1

In [72]:
lab_names = {
    '50983': 'Sodium',
    '50971': 'Potassium',
    '50902': 'Chloride',
    '50882': 'Bicarbonate',
    '50912': 'Creatinine',
    '51006': 'BUN',
    '50931': 'Glucose',
    '50893': 'Calcium',
    '50868': 'Anion Gap',
    '51222': 'Hemoglobin',
    '51301': 'WBC',
    '51265': 'Platelet Count',
    '51221': 'Hematocrit',
    '51250': 'MCV',
    '51277': 'RDW',
    '50960': 'Magnesium',
    '50970': 'Phosphate',
    '51248': 'MCH',
    '51249': 'MCHC',
    '51279': 'RBC'
}

icd_names = {
    'I10': 'Essential (primary) hypertension',
    'E785': 'Hyperlipidemia, unspecified',
    'K219': 'Gastroesophageal reflux disease without esophagitis',
    'Z87891': 'Personal history of nicotine dependence',
    'I2510': 'Atherosclerotic heart disease of native coronary artery without angina pectoris',
    'N179': 'Acute kidney failure, unspecified',
    'F329': 'Major depressive disorder, single episode, unspecified',
    'I4891': 'Unspecified atrial fibrillation',
    'Z7901': 'Long term (current) use of anticoagulants',
    'F419': 'Anxiety disorder, unspecified',
    'E119': 'Type 2 diabetes mellitus without complications',
    'E039': 'Hypothyroidism, unspecified',
    'Z794': 'Long term (current) use of insulin',
    'D649': 'Anemia, unspecified',
    'N390': 'Urinary tract infection, site not specified'
}

ccsr_names = {
    'FAC021': 'Personal/family history of disease',
    'FAC025': 'Other specified status',
    'END011': 'Fluid and electrolyte disorders',
    'CIR011': 'Coronary atherosclerosis and other heart disease',
    'END010': 'Disorders of lipid metabolism',
    'CIR007': 'Essential hypertension',
    'END003': 'Diabetes mellitus with complication',
    'CIR019': 'Heart failure',
    'DIG004': 'Esophageal disorders',
    'CIR017': 'Cardiac dysrhythmias',
    'CIR008': 'Hypertension with complications and secondary hypertension',
    'BLD003': 'Aplastic anemia',
    'EXT027': 'External cause codes: place of occurrence of the external cause',
    'GEN002': 'Acute and unspecified renal failure',
    'END009': 'Obesity'
}

def map_feature_name(feature_name):
    if feature_name.startswith('lab_') and feature_name.endswith('_daily'):
        code = feature_name.replace('lab_', '').replace('_daily', '')
        if code in lab_names:
            return f"{lab_names[code]} ({code})"
    elif feature_name.startswith('icd_'):
        code = feature_name.replace('icd_', '')
        if code in icd_names:
            return f"{icd_names[code]} ({code})"
    elif feature_name.startswith('ccsr_'):
        code = feature_name.replace('ccsr_', '')
        if code in ccsr_names:
            return f"{ccsr_names[code]} ({code})"
    return feature_name

In [73]:
def get_patient_analysis(subject_id, hadm_id):
    patient_delta = total_deltas[
        (total_deltas['subject_id'] == subject_id) & 
        (total_deltas['hadm_id'] == hadm_id)
    ].copy()
    print(f"Actual risk: {patient_delta['risk_actual_mean'].iloc[0]:.4f}")
    patient_shap = shap_matrix[shap_matrix['hadm_id'] == hadm_id].copy()
    shap_features = patient_shap.drop('hadm_id', axis=1).T
    shap_features.columns = ['shap_value']
    shap_features['feature'] = shap_features.index
    
    combined = patient_delta.merge(shap_features, on='feature', how='inner')
    combined['delta_abs'] = combined['delta_mean'].abs()
    combined['shap_abs'] = combined['shap_value'].abs()
    
    return {
        'patient_id': subject_id,
        'hadm_id': hadm_id,
        'n_days': patient_delta['los'].iloc[0],
        'risk_actual': patient_delta['risk_actual_mean'].iloc[0],
        'combined': combined,
        'by_delta': combined.sort_values('delta_abs', ascending=False),
        'by_shap': combined.sort_values('shap_abs', ascending=False)
    }

def interpret_delta(delta, mode_direction):
    if mode_direction == 'add':
        if delta > 0:
            return "without → ↑ risk"
        elif delta < 0:
            return "without → ↓ risk"

    elif mode_direction == 'remove':
        if delta < 0:
            return "with → ↓ risk"
        elif delta > 0:
            return "with → ↑ risk"

    elif mode_direction == 'increase_to_mean':
        if delta < 0:
            return "lower than mean → ↓ risk"
        elif delta > 0:
            return "lower than mean → ↑ risk"
    
    elif mode_direction == 'reduce_to_mean':
        if delta < 0:
            return "higher than mean → ↓ risk"
        elif delta > 0:
            return "higher than mean → ↑ risk"
    
    elif mode_direction == 'low':
        if delta > 0:
            return "low → ↑ risk"
        elif delta < 0:
            return "low → ↓ risk"

    elif mode_direction == 'high':
        if delta > 0:
            return "high → ↑ risk"
        elif delta < 0:
            return "high → ↓ risk"
    
    elif mode_direction == 'normal':
        if delta > 0:
            return "normal range → ↑ risk"
        elif delta < 0:
            return "normal range → ↓ risk"

    elif mode_direction == 'older':
        if delta < 0:
            return "older → ↓ risk"
        elif delta > 0:
            return "older → ↑ risk"
    
    elif mode_direction == 'younger':
        if delta > 0:
            return "younger → ↑ risk"
        elif delta < 0:
            return "younger → ↓ risk"

    elif mode_direction == 'opposite':
        if delta > 0:
            return "↑ risk"
        elif delta < 0:
            return "↓ risk"

In [74]:
patient_info = total_data.copy()
icd_cols = [col for col in total_data.columns if col.startswith('icd_')]
ccsr_cols = [col for col in total_data.columns if col.startswith('ccsr_')]
lab_cols = [col for col in total_data.columns if col.startswith('lab_') and col.endswith('_daily')]

patient_info['icd_count'] = patient_info[icd_cols].sum(axis=1)
patient_info['ccsr_count'] = patient_info[ccsr_cols].sum(axis=1)
patient_info['lab_count'] = patient_info[lab_cols].notna().sum(axis=1)

patient_info = patient_info[
    (patient_info['icd_count'] >= 1) & (patient_info['ccsr_count'] >= 1) &
    (patient_info['lab_count'] >= 1)
].copy()

age_groups = {
    'young': (18, 40),
    'middle': (40, 65),
    'elderly': (65, 80),
    'very_elderly': (80, 120)
}

def get_age_group(age):
    for group, (low, high) in age_groups.items():
        if low <= age < high:
            return group
    return 'unknown'

patient_info = patient_info[['subject_id', 'hadm_id', 'gender_male', 'age', 'los', 'icd_count', 'ccsr_count', 'lab_count', 'target_readmission_30d']]
patient_info['age_group'] = patient_info['age'].apply(get_age_group)

print(f"Patient info created:")
print(f"  Total hospitalizations: {len(patient_info)}")
print(f"  With readmission: {patient_info['target_readmission_30d'].sum():.0f}")
print(f"  Without readmission: {len(patient_info) - patient_info['target_readmission_30d'].sum():.0f}")

def get_stratified_sample(patient_info, sample_size=20, random_state=42):
    readmission_yes = patient_info[patient_info['target_readmission_30d'] == 1]
    readmission_no = patient_info[patient_info['target_readmission_30d'] == 0]
    
    n_total = sample_size
    n_yes = n_total // 2
    n_no = n_total - n_yes
    samples = []

    for group, label, n in [(readmission_yes, 'with_readmission', n_yes), 
                            (readmission_no, 'without_readmission', n_no)]:
       
        age_groups_list = group['age_group'].unique()
        n_per_age = n // len(age_groups_list) if len(age_groups_list) > 0 else 0
        remainder = n - n_per_age * len(age_groups_list)
        
        for i, age_group in enumerate(age_groups_list):
            age_group_patients = group[group['age_group'] == age_group]

            n_age = n_per_age + (1 if i < remainder else 0)
            if n_age == 0:
                continue

            male = age_group_patients[age_group_patients['gender_male'] == 1]
            female = age_group_patients[age_group_patients['gender_male'] == 0]
            
            n_male_age = min(n_age // 2, len(male))
            n_female_age = n_age - n_male_age
            
            if len(male) < n_male_age:
                n_male_age = len(male)
                n_female_age = n_age - n_male_age
            
            if len(female) < n_female_age:
                n_female_age = len(female)
                n_male_age = n_age - n_female_age
            
            if len(male) > 0 and n_male_age > 0:
                sample_male = male.sample(n=min(n_male_age, len(male)), random_state=random_state)
                samples.append(sample_male)
            
            if len(female) > 0 and n_female_age > 0:
                sample_female = female.sample(n=min(n_female_age, len(female)), random_state=random_state)
                samples.append(sample_female)

    if len(samples) > 0:
        sample = pd.concat(samples).sample(frac=1, random_state=random_state)
    else:
        print("No samples selected")
        return pd.DataFrame()
    
    print(f"\nSelected {len(sample)} hospitalizations")
    print(f"   With readmission: {sample['target_readmission_30d'].sum():.0f}")
    print(f"   Without readmission: {len(sample) - sample['target_readmission_30d'].sum():.0f}")
    print(f"   Male: {sample['gender_male'].sum():.0f}")
    print(f"   Female: {len(sample) - sample['gender_male'].sum():.0f}")
    
    print(f"\nAge groups in sample:")
    print(sample['age_group'].value_counts().sort_index())
    
    return sample

SAMPLE_SIZE = 16
sample_patients_df = get_stratified_sample(patient_info, sample_size=SAMPLE_SIZE, random_state=42)
sample_patients_df

Patient info created:
  Total hospitalizations: 34892
  With readmission: 6498
  Without readmission: 28394

Selected 16 hospitalizations
   With readmission: 8
   Without readmission: 8
   Male: 8
   Female: 8

Age groups in sample:
age_group
elderly         4
middle          4
very_elderly    4
young           4
Name: count, dtype: int64

,subject_id,hadm_id,gender_male,age,los,icd_count,ccsr_count,lab_count,target_readmission_30d,age_group
9380,11618742,28081676,1,76,9,3.0,9,20,1,elderly
56263,19622090,25925869,0,75,4,3.0,3,20,1,elderly
924,10164170,24771340,0,87,5,3.0,4,20,1,very_elderly
15166,12592821,29232336,1,30,6,1.0,2,20,0,young
45388,17780345,26440784,0,71,3,1.0,5,20,0,elderly
15279,12610089,21423469,0,60,7,3.0,3,20,0,middle
9846,11698781,20902547,1,88,3,1.0,2,20,0,very_elderly
38937,16668434,23499682,0,80,6,2.0,3,20,0,very_elderly
1738,10301630,26672817,1,57,23,6.0,10,20,1,middle
47097,18056725,25708121,0,32,4,2.0,3,20,0,young
58220,19972786,29611193,1,81,4,1.0,7,20,1,very_elderly
33636,15794497,25969239,0,37,6,1.0,3,20,1,young
3995,10692997,24362796,1,61,2,4.0,3,20,0,middle
26215,14507136,28573487,1,66,4,4.0,5,20,0,elderly
55155,19424524,26254319,0,58,4,3.0,4,20,1,middle
5762,11011770,28546869,1,30,2,4.0,3,17,1,young

In [75]:
def get_patient_full_data_with_analysis(subject_id, hadm_id, total_data):

    patient_raw = total_data[
        (total_data['subject_id'] == subject_id) & 
        (total_data['hadm_id'] == hadm_id)
    ]

    patient = patient_raw.iloc[0].to_dict()
    clean_data = {
        'subject_id': subject_id,
        'hadm_id': hadm_id,
        'age': patient.get('age'),
        'gender': 'Male' if patient.get('gender_male') == 1 else 'Female',
        'los': patient.get('los'),
        'readmission': 'Yes' if patient.get('target_readmission_30d') == 1 else 'No',
    }
    
    icd_cols = [col for col in total_data.columns if col.startswith('icd_')]
    icd_present = [col for col in icd_cols if col in patient and patient[col] == 1]
    
    ccsr_cols = [col for col in total_data.columns if col.startswith('ccsr_')]
    ccsr_present = [col for col in ccsr_cols if col in patient and patient[col] == 1]
    
    lab_cols = [col for col in total_data.columns if col.startswith('lab_') and col.endswith('_daily')]
    lab_present = {col: patient[col] for col in lab_cols if col in patient and pd.notna(patient[col])}
    
    clean_data['icd_diagnoses'] = [map_feature_name(col) for col in icd_present]
    clean_data['icd_count'] = len(icd_present)
    
    clean_data['ccsr_diagnoses'] = [map_feature_name(col) for col in ccsr_present]
    clean_data['ccsr_count'] = len(ccsr_present)
    
    clean_data['lab_values'] = {map_feature_name(col): val for col, val in lab_present.items()}
    clean_data['lab_count'] = len(lab_present)
    
    other_features = ['num_diagnoses', 'num_chronic', 'comorbidity_score',
                      'num_medications_daily', 'prior_admissions_12mo',
                      'cumulative_procedures', 'cumulative_medications',
                      'num_procedures_daily']
    
    for feat in other_features:
        if feat in patient and pd.notna(patient[feat]):
            clean_data[feat] = patient[feat]
    
    race_cols = [col for col in total_data.columns if col.startswith('race_')]
    for col in race_cols:
        if col in patient and patient[col] == 1:
            clean_data['race'] = col.replace('race_', '').replace('_', ' ').title()
            break
    if 'race' not in clean_data:
        clean_data['race'] = 'Unknown'
    
    insurance_cols = [col for col in total_data.columns if col.startswith('insurance_')]
    for col in insurance_cols:
        if col in patient and patient[col] == 1:
            clean_data['insurance'] = col.replace('insurance_', '')
            break
    if 'insurance' not in clean_data:
        clean_data['insurance'] = 'Unknown'
    
    admission_type_cols = [col for col in total_data.columns if col.startswith('admission_type_')]
    for col in admission_type_cols:
        if col in patient and patient[col] == 1:
            adm_type = col.replace('admission_type_', '').replace('_', ' ').title()
            clean_data['admission_type'] = adm_type
            break
    if 'admission_type' not in clean_data:
        clean_data['admission_type'] = 'Unknown'
    
    discharge_cols = [col for col in total_data.columns if col.startswith('discharge_location_')]
    for col in discharge_cols:
        if col in patient and patient[col] == 1:
            discharge = col.replace('discharge_location_', '').replace('_', ' ').title()
            clean_data['discharge_location'] = discharge
            break
    if 'discharge_location' not in clean_data:
        clean_data['discharge_location'] = 'Unknown'
    
    adm_location_cols = [col for col in total_data.columns if col.startswith('admission_location_')]
    for col in adm_location_cols:
        if col in patient and patient[col] == 1:
            adm_loc = col.replace('admission_location_', '').replace('_', ' ').title()
            clean_data['admission_location'] = adm_loc
            break
    if 'admission_location' not in clean_data:
        clean_data['admission_location'] = 'Unknown'

    result = get_patient_analysis(subject_id, hadm_id)
    if result:
        existing_features_original = icd_present + ccsr_present + list(lab_present.keys())
        result['combined'] = result['combined'][
            result['combined']['feature'].isin(existing_features_original)
        ]
        
        result['by_delta'] = result['combined'].sort_values('delta_abs', ascending=False)
        result['by_shap'] = result['combined'].sort_values('shap_abs', ascending=False)
        
        result['combined']['feature_display'] = result['combined']['feature'].apply(map_feature_name)
        result['by_delta']['feature_display'] = result['by_delta']['feature'].apply(map_feature_name)
        result['by_shap']['feature_display'] = result['by_shap']['feature'].apply(map_feature_name)
        
        if len(result['by_delta']) > 0:
            result['by_delta']['interpretation'] = result['by_delta'].apply(
                lambda row: interpret_delta(row['delta_mean'], row['direction_mode']), axis=1
            )
        
        if len(result['by_shap']) > 0:
            result['by_shap']['interpretation'] = result['by_shap'].apply(
                lambda row: interpret_delta(row['delta_mean'], row['direction_mode']), axis=1
            )
        clean_data['analysis'] = result
    
    return clean_data


def print_patient_full_with_analysis(clean_data):
    if clean_data is None:
        return
        
    print(f"\nDEMOGRAPHICS:")
    print(f"  Age: {clean_data['age']}")
    print(f"  Gender: {clean_data['gender']}")
    print(f"  Race: {clean_data.get('race', 'Unknown')}")
    print(f"  Insurance: {clean_data.get('insurance', 'Unknown')}")
    print(f"  LOS: {clean_data['los']} days")
    print(f"  Readmission: {clean_data['readmission']}")

    print(f"\nADMISSION DETAILS:")
    print(f"  Admission Type: {clean_data.get('admission_type', 'Unknown')}")
    print(f"  Admission Location: {clean_data.get('admission_location', 'Unknown')}")
    print(f"  Discharge Location: {clean_data.get('discharge_location', 'Unknown')}")
    
    if clean_data['icd_count'] > 0:
        print(f"\nICD DIAGNOSES ({clean_data['icd_count']}):")
        for dx in clean_data['icd_diagnoses']:
            print(f"  - {dx}")
    
    if clean_data['ccsr_count'] > 0:
        print(f"\nCCSR CATEGORIES ({clean_data['ccsr_count']}):")
        for ccsr in clean_data['ccsr_diagnoses']:
            print(f"  - {ccsr}")
    
    if clean_data['lab_count'] > 0:
        print(f"\nLAB VALUES ({clean_data['lab_count']}):")
        for lab, value in clean_data['lab_values'].items():
            print(f"  - {lab}: {value:.2f}")
    
    other_feats = ['num_diagnoses', 'num_chronic', 'comorbidity_score',
                   'num_medications_daily', 'prior_admissions_12mo',
                   'cumulative_procedures', 'cumulative_medications',
                   'num_procedures_daily']
    
    print(f"\nOTHER FEATURES:")
    for feat in other_feats:
        if feat in clean_data:
            print(f"  {feat}: {clean_data[feat]:.2f}")
    
    if 'analysis' in clean_data and clean_data['analysis']:
        result = clean_data['analysis']
        
        print(f"\nDELTA/SHAP:")
        if len(result['by_delta']) > 0:
            print(result['by_delta'][['feature_display', 'delta_mean', 'shap_value', 'interpretation']].to_string(index=False))

### Middle

In [76]:
SUBJECT_ID = 10301630
HADM_ID = 26672817
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.3520

DEMOGRAPHICS:
  Age: 57
  Gender: Male
  Race: White
  Insurance: Private
  LOS: 23 days
  Readmission: Yes

ADMISSION DETAILS:
  Admission Type: Observation Admit
  Admission Location: Clinic Referral
  Discharge Location: Home Health Care

ICD DIAGNOSES (6):
  - Essential (primary) hypertension (I10)
  - Gastroesophageal reflux disease without esophagitis (K219)
  - Personal history of nicotine dependence (Z87891)
  - Atherosclerotic heart disease of native coronary artery without angina pectoris (I2510)
  - Acute kidney failure, unspecified (N179)
  - Anemia, unspecified (D649)

CCSR CATEGORIES (10):
  - Personal/family history of disease (FAC021)
  - Other specified status (FAC025)
  - Fluid and electrolyte disorders (END011)
  - Coronary atherosclerosis and other heart disease (CIR011)
  - Disorders of lipid metabolism (END010)
  - Essential hypertension (CIR007)
  - Esophageal disorders (DIG004)
  - Aplastic anemia (BLD003)
  - External cause codes: place of occurrence of the external cause (EXT027)
  - Acute and unspecified renal failure (GEN002)

LAB VALUES (20):
  - Anion Gap (50868): 16.00
  - Bicarbonate (50882): 24.35
  - Calcium (50893): 8.72
  - Chloride (50902): 99.13
  - Creatinine (50912): 0.79
  - Glucose (50931): 128.13
  - Magnesium (50960): 2.01
  - Phosphate (50970): 3.90
  - Potassium (50971): 4.42
  - Sodium (50983): 139.48
  - BUN (51006): 30.17
  - Hematocrit (51221): 25.68
  - Hemoglobin (51222): 7.87
  - MCH (51248): 25.72
  - MCHC (51249): 30.65
  - MCV (51250): 83.86
  - Platelet Count (51265): 413.50
  - RDW (51277): 15.51
  - RBC (51279): 3.06
  - WBC (51301): 9.20

OTHER FEATURES:
  num_diagnoses: 736.00
  num_chronic: 345.00
  comorbidity_score: 8.00
  num_medications_daily: 19.83
  prior_admissions_12mo: 1.00
  cumulative_procedures: 5.48
  cumulative_medications: 239.26
  num_procedures_daily: 0.35

DELTA/SHAP:
                                                                        feature_display    delta_mean  shap_value        interpretation
                                                                            RBC (51279)  3.310445e-02    0.031430          low → ↑ risk
                                                                            RDW (51277)  1.711824e-02    0.052001         high → ↑ risk
                                                                     Hematocrit (51221)  1.698685e-02    0.035869          low → ↑ risk
                                                               Aplastic anemia (BLD003)  4.866715e-03    0.028390         with → ↑ risk
                                                                     Hemoglobin (51222)  4.818496e-03    0.017265          low → ↑ risk
                                                                 Platelet Count (51265)  4.535342e-03    0.020762 normal range → ↑ risk
                                                                            MCH (51248) -4.461560e-03   -0.014423          low → ↓ risk
                                                                            WBC (51301)  3.205595e-03    0.008397         high → ↑ risk
                                                                        Calcium (50893)  2.298901e-03    0.002588 normal range → ↑ risk
                                               Fluid and electrolyte disorders (END011)  2.166245e-03    0.013912         with → ↑ risk
                                                                        Glucose (50931)  1.928763e-03    0.003080         high → ↑ risk
                                                                           MCHC (51249) -1.888253e-03   -0.012513 normal range → ↓ risk
                                                 Disorders of lipid metabolism (END010) -1.688198e-03   -0.007227         with → ↓ risk
                                                          Esophageal disorders (DIG004) -1.634260e-03   -0.000874         with → ↓ risk
                                                                            BUN (51006) -1.621632e-03    0.004132         high → ↓ risk
                                                                     Creatinine (50912)  1.580995e-03    0.001882          low → ↑ risk
                                                        Other specified status (FAC025)  1.552843e-03    0.002432         with → ↑ risk
                                                             Anemia, unspecified (D649)  6.734609e-04   -0.001089         with → ↑ risk
                                                                      Magnesium (50960) -6.167974e-04    0.001776 normal range → ↓ risk
                                       Personal history of nicotine dependence (Z87891) -4.195883e-04   -0.002901         with → ↓ risk
                                               Acute kidney failure, unspecified (N179)  3.495200e-04    0.004846         with → ↑ risk
                                                                      Anion Gap (50868)  2.718039e-04    0.009097 normal range → ↑ risk
                                                                       Chloride (50902)  2.374309e-04    0.007324 normal range → ↑ risk
               External cause codes: place of occurrence of the external cause (EXT027) -6.820906e-05   -0.012672         with → ↓ risk
                                           Acute and unspecified renal failure (GEN002) -6.535161e-05    0.002952         with → ↓ risk
                                                                      Phosphate (50970) -6.126696e-05    0.002423 normal range → ↓ risk
                              Coronary atherosclerosis and other heart disease (CIR011)  4.409174e-05    0.001083         with → ↑ risk
                                            Personal/family history of disease (FAC021)  3.963483e-05    0.000248         with → ↑ risk
                             Gastroesophageal reflux disease without esophagitis (K219)  1.660000e-05   -0.000486         with → ↑ risk
                                                        Essential hypertension (CIR007) -1.172257e-05    0.002868         with → ↓ risk
                                                                      Potassium (50971)  6.216601e-07    0.003399 normal range → ↑ risk
                                                                         Sodium (50983)  0.000000e+00   -0.014792                  None
                                                                            MCV (51250)  0.000000e+00   -0.005626                  None
                                                                    Bicarbonate (50882)  0.000000e+00   -0.000615                  None
Atherosclerotic heart disease of native coronary artery without angina pectoris (I2510)  0.000000e+00    0.000991                  None
                                                 Essential (primary) hypertension (I10)  0.000000e+00   -0.001015                  None

In [77]:
SUBJECT_ID = 10692997
HADM_ID = 24362796
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.1249

DEMOGRAPHICS:
  Age: 61
  Gender: Male
  Race: White
  Insurance: Medicare
  LOS: 2 days
  Readmission: No

ADMISSION DETAILS:
  Admission Type: Surgical Same Day Admission
  Admission Location: Physician Referral
  Discharge Location: Home

ICD DIAGNOSES (4):
  - Essential (primary) hypertension (I10)
  - Gastroesophageal reflux disease without esophagitis (K219)
  - Personal history of nicotine dependence (Z87891)
  - Type 2 diabetes mellitus without complications (E119)

CCSR CATEGORIES (3):
  - Personal/family history of disease (FAC021)
  - Essential hypertension (CIR007)
  - Esophageal disorders (DIG004)

LAB VALUES (20):
  - Anion Gap (50868): 13.00
  - Bicarbonate (50882): 27.00
  - Calcium (50893): 9.10
  - Chloride (50902): 100.00
  - Creatinine (50912): 1.00
  - Glucose (50931): 188.00
  - Magnesium (50960): 2.20
  - Phosphate (50970): 2.60
  - Potassium (50971): 4.10
  - Sodium (50983): 136.00
  - BUN (51006): 11.00
  - Hematocrit (51221): 36.50
  - Hemoglobin (51222): 11.80
  - MCH (51248): 30.00
  - MCHC (51249): 32.30
  - MCV (51250): 93.00
  - Platelet Count (51265): 247.00
  - RDW (51277): 12.80
  - RBC (51279): 3.93
  - WBC (51301): 16.10

OTHER FEATURES:
  num_diagnoses: 14.00
  num_chronic: 12.00
  comorbidity_score: 2.00
  num_medications_daily: 15.50
  prior_admissions_12mo: 0.00
  cumulative_procedures: 2.00
  cumulative_medications: 23.00
  num_procedures_daily: 1.00

DELTA/SHAP:
                                           feature_display  delta_mean  shap_value        interpretation
                                               WBC (51301)    0.005003    0.029377 normal range → ↑ risk
                                               RBC (51279)    0.003349   -0.010649 normal range → ↑ risk
          Personal history of nicotine dependence (Z87891)   -0.003229   -0.011870         with → ↓ risk
Gastroesophageal reflux disease without esophagitis (K219)   -0.002662   -0.006404         with → ↓ risk
                                        Hemoglobin (51222)    0.002417   -0.015836 normal range → ↑ risk
     Type 2 diabetes mellitus without complications (E119)    0.002081    0.011030         with → ↑ risk
                    Essential (primary) hypertension (I10)   -0.001471   -0.005312         with → ↓ risk
                                         Magnesium (50960)   -0.000814   -0.005824 normal range → ↓ risk
               Personal/family history of disease (FAC021)   -0.000494    0.000180         with → ↓ risk
                             Esophageal disorders (DIG004)   -0.000386    0.000579         with → ↓ risk
                                           Glucose (50931)    0.000190    0.006828 normal range → ↑ risk
                                         Phosphate (50970)    0.000183   -0.002116 normal range → ↑ risk
                                        Hematocrit (51221)   -0.000041   -0.044649 normal range → ↓ risk
                           Essential hypertension (CIR007)    0.000000    0.005818                  None
                                               RDW (51277)    0.000000   -0.086777                  None
                                    Platelet Count (51265)    0.000000   -0.009986                  None
                                               MCV (51250)    0.000000    0.005485                  None
                                              MCHC (51249)    0.000000    0.001751                  None
                                               MCH (51248)    0.000000    0.003426                  None
                                         Anion Gap (50868)    0.000000    0.003110                  None
                                       Bicarbonate (50882)    0.000000   -0.000803                  None
                                            Sodium (50983)    0.000000   -0.003383                  None
                                         Potassium (50971)    0.000000   -0.005737                  None
                                        Creatinine (50912)    0.000000   -0.000431                  None
                                          Chloride (50902)    0.000000    0.000482                  None
                                           Calcium (50893)    0.000000   -0.007076                  None
                                               BUN (51006)    0.000000   -0.008781                  None

In [78]:
SUBJECT_ID = 12610089
HADM_ID = 21423469
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.1124

DEMOGRAPHICS:
  Age: 60
  Gender: Female
  Race: Other
  Insurance: Private
  LOS: 7 days
  Readmission: No

ADMISSION DETAILS:
  Admission Type: Observation Admit
  Admission Location: Transfer From Hospital
  Discharge Location: Home

ICD DIAGNOSES (3):
  - Essential (primary) hypertension (I10)
  - Personal history of nicotine dependence (Z87891)
  - Type 2 diabetes mellitus without complications (E119)

CCSR CATEGORIES (3):
  - Personal/family history of disease (FAC021)
  - Essential hypertension (CIR007)
  - Aplastic anemia (BLD003)

LAB VALUES (20):
  - Anion Gap (50868): 12.71
  - Bicarbonate (50882): 22.57
  - Calcium (50893): 8.73
  - Chloride (50902): 102.29
  - Creatinine (50912): 0.66
  - Glucose (50931): 135.14
  - Magnesium (50960): 2.16
  - Phosphate (50970): 2.71
  - Potassium (50971): 3.91
  - Sodium (50983): 137.57
  - BUN (51006): 9.57
  - Hematocrit (51221): 31.40
  - Hemoglobin (51222): 10.30
  - MCH (51248): 28.56
  - MCHC (51249): 32.81
  - MCV (51250): 87.00
  - Platelet Count (51265): 372.57
  - RDW (51277): 12.47
  - RBC (51279): 3.61
  - WBC (51301): 11.61

OTHER FEATURES:
  num_diagnoses: 70.00
  num_chronic: 56.00
  comorbidity_score: 0.00
  num_medications_daily: 9.71
  prior_admissions_12mo: 0.00
  cumulative_procedures: 1.00
  cumulative_medications: 36.86
  num_procedures_daily: 0.14

DELTA/SHAP:
                                      feature_display  delta_mean  shap_value        interpretation
                                   Hemoglobin (51222)    0.009184    0.017147          low → ↑ risk
                                          WBC (51301)    0.007411    0.019565         high → ↑ risk
                                   Hematocrit (51221)    0.007410    0.021889          low → ↑ risk
                             Aplastic anemia (BLD003)    0.006301    0.049321         with → ↑ risk
                                          RBC (51279)    0.003546    0.003475          low → ↑ risk
                               Platelet Count (51265)    0.002399    0.070780 normal range → ↑ risk
                                          BUN (51006)    0.001618    0.000772 normal range → ↑ risk
          Personal/family history of disease (FAC021)    0.001495    0.003856         with → ↑ risk
                                    Phosphate (50970)   -0.001231   -0.004498 normal range → ↓ risk
Type 2 diabetes mellitus without complications (E119)    0.000929    0.008068         with → ↑ risk
                                      Glucose (50931)    0.000895    0.003606         high → ↑ risk
                                    Magnesium (50960)   -0.000758    0.001703         high → ↓ risk
                                      Calcium (50893)    0.000396    0.005163 normal range → ↑ risk
                                   Creatinine (50912)    0.000320    0.002601          low → ↑ risk
     Personal history of nicotine dependence (Z87891)    0.000234   -0.001898         with → ↑ risk
                                  Bicarbonate (50882)   -0.000144   -0.001254 normal range → ↓ risk
                                     Chloride (50902)   -0.000106    0.010566 normal range → ↓ risk
               Essential (primary) hypertension (I10)    0.000054   -0.001265         with → ↑ risk
                                       Sodium (50983)    0.000000    0.009474                  None
                                    Anion Gap (50868)    0.000000    0.000440                  None
                                          MCH (51248)    0.000000    0.002871                  None
                                         MCHC (51249)    0.000000    0.005217                  None
                                          MCV (51250)    0.000000    0.002205                  None
                      Essential hypertension (CIR007)    0.000000    0.004385                  None
                                          RDW (51277)    0.000000   -0.135740                  None
                                    Potassium (50971)    0.000000    0.009599                  None

In [79]:
SUBJECT_ID = 19424524
HADM_ID = 26254319
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.4641

DEMOGRAPHICS:
  Age: 58
  Gender: Female
  Race: White
  Insurance: Private
  LOS: 4 days
  Readmission: Yes

ADMISSION DETAILS:
  Admission Type: Ew Emer.
  Admission Location: Emergency Room
  Discharge Location: Home Health Care

ICD DIAGNOSES (3):
  - Personal history of nicotine dependence (Z87891)
  - Acute kidney failure, unspecified (N179)
  - Anxiety disorder, unspecified (F419)

CCSR CATEGORIES (4):
  - Personal/family history of disease (FAC021)
  - Fluid and electrolyte disorders (END011)
  - Aplastic anemia (BLD003)
  - Acute and unspecified renal failure (GEN002)

LAB VALUES (20):
  - Anion Gap (50868): 15.00
  - Bicarbonate (50882): 18.75
  - Calcium (50893): 8.57
  - Chloride (50902): 106.25
  - Creatinine (50912): 1.40
  - Glucose (50931): 93.00
  - Magnesium (50960): 1.82
  - Phosphate (50970): 2.97
  - Potassium (50971): 4.08
  - Sodium (50983): 136.00
  - BUN (51006): 18.00
  - Hematocrit (51221): 23.15
  - Hemoglobin (51222): 7.72
  - MCH (51248): 30.40
  - MCHC (51249): 32.85
  - MCV (51250): 92.50
  - Platelet Count (51265): 75.25
  - RDW (51277): 15.10
  - RBC (51279): 2.45
  - WBC (51301): 3.58

OTHER FEATURES:
  num_diagnoses: 76.00
  num_chronic: 16.00
  comorbidity_score: 6.00
  num_medications_daily: 15.75
  prior_admissions_12mo: 3.00
  cumulative_procedures: 0.50
  cumulative_medications: 37.75
  num_procedures_daily: 0.25

DELTA/SHAP:
                                 feature_display  delta_mean  shap_value        interpretation
                                     RBC (51279)    0.038402    0.060256          low → ↑ risk
                                     RDW (51277)    0.035135    0.026417         high → ↑ risk
                          Platelet Count (51265)    0.022296    0.075332          low → ↑ risk
                              Hematocrit (51221)    0.020524    0.047561          low → ↑ risk
        Fluid and electrolyte disorders (END011)    0.011565    0.026449         with → ↑ risk
                              Hemoglobin (51222)    0.008367    0.016957          low → ↑ risk
                                  Sodium (50983)    0.005964    0.020617 normal range → ↑ risk
                                Chloride (50902)   -0.004932   -0.010510         high → ↓ risk
                                     WBC (51301)    0.003245    0.003986          low → ↑ risk
     Personal/family history of disease (FAC021)   -0.001164   -0.000320         with → ↓ risk
        Acute kidney failure, unspecified (N179)    0.001074    0.005032         with → ↑ risk
                        Aplastic anemia (BLD003)    0.000946    0.022174         with → ↑ risk
            Anxiety disorder, unspecified (F419)    0.000763    0.005859         with → ↑ risk
                               Magnesium (50960)   -0.000707    0.004788 normal range → ↓ risk
Personal history of nicotine dependence (Z87891)   -0.000597   -0.004029         with → ↓ risk
                                 Calcium (50893)    0.000338    0.002737          low → ↑ risk
                             Bicarbonate (50882)    0.000165   -0.000350          low → ↑ risk
                              Creatinine (50912)   -0.000152   -0.001066         high → ↓ risk
    Acute and unspecified renal failure (GEN002)   -0.000109    0.002139         with → ↓ risk
                                 Glucose (50931)    0.000035    0.002435 normal range → ↑ risk
                               Phosphate (50970)    0.000000    0.000366                  None
                               Potassium (50971)    0.000000    0.001653                  None
                                     BUN (51006)    0.000000   -0.004577                  None
                                     MCH (51248)    0.000000    0.009713                  None
                                    MCHC (51249)    0.000000    0.002956                  None
                                     MCV (51250)    0.000000    0.001624                  None
                               Anion Gap (50868)    0.000000    0.006391                  None

### Young

In [80]:
SUBJECT_ID = 15794497
HADM_ID = 25969239	
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.5623

DEMOGRAPHICS:
  Age: 37
  Gender: Female
  Race: Black/African American
  Insurance: Medicaid
  LOS: 6 days
  Readmission: Yes

ADMISSION DETAILS:
  Admission Type: Ew Emer.
  Admission Location: Walk-In/Self Referral
  Discharge Location: Home Health Care

ICD DIAGNOSES (1):
  - Long term (current) use of anticoagulants (Z7901)

CCSR CATEGORIES (3):
  - Personal/family history of disease (FAC021)
  - Other specified status (FAC025)
  - Aplastic anemia (BLD003)

LAB VALUES (20):
  - Anion Gap (50868): 10.50
  - Bicarbonate (50882): 26.00
  - Calcium (50893): 8.72
  - Chloride (50902): 99.50
  - Creatinine (50912): 0.50
  - Glucose (50931): 98.83
  - Magnesium (50960): 1.70
  - Phosphate (50970): 3.77
  - Potassium (50971): 3.57
  - Sodium (50983): 136.00
  - BUN (51006): 8.00
  - Hematocrit (51221): 24.27
  - Hemoglobin (51222): 7.88
  - MCH (51248): 31.58
  - MCHC (51249): 32.48
  - MCV (51250): 97.50
  - Platelet Count (51265): 137.67
  - RDW (51277): 16.18
  - RBC (51279): 2.49
  - WBC (51301): 3.07

OTHER FEATURES:
  num_diagnoses: 114.00
  num_chronic: 54.00
  comorbidity_score: 6.00
  num_medications_daily: 22.50
  prior_admissions_12mo: 7.00
  cumulative_procedures: 0.17
  cumulative_medications: 74.83
  num_procedures_daily: 0.17

DELTA/SHAP:
                                  feature_display  delta_mean  shap_value        interpretation
                                      RDW (51277)    0.023897    0.067159         high → ↑ risk
                                      RBC (51279)    0.014012    0.032516          low → ↑ risk
                               Hematocrit (51221)    0.007311    0.031999          low → ↑ risk
                               Hemoglobin (51222)    0.005277    0.014755          low → ↑ risk
                                   Sodium (50983)    0.002402    0.016727 normal range → ↑ risk
                               Creatinine (50912)    0.001927    0.007283          low → ↑ risk
                                      WBC (51301)    0.001786    0.006718          low → ↑ risk
Long term (current) use of anticoagulants (Z7901)   -0.000913   -0.000070         with → ↓ risk
                                      MCH (51248)    0.000652    0.011244 normal range → ↑ risk
                                      BUN (51006)    0.000614   -0.002796          low → ↑ risk
                                Potassium (50971)   -0.000550   -0.000189 normal range → ↓ risk
                                Anion Gap (50868)   -0.000543   -0.007039 normal range → ↓ risk
                         Aplastic anemia (BLD003)    0.000503    0.020146         with → ↑ risk
                  Other specified status (FAC025)    0.000323    0.004426         with → ↑ risk
      Personal/family history of disease (FAC021)    0.000240    0.001656         with → ↑ risk
                           Platelet Count (51265)    0.000225   -0.022416          low → ↑ risk
                                Magnesium (50960)   -0.000173    0.007091 normal range → ↓ risk
                                  Glucose (50931)    0.000063   -0.001885 normal range → ↑ risk
                                 Chloride (50902)    0.000000    0.006938                  None
                                Phosphate (50970)    0.000000    0.003389                  None
                                  Calcium (50893)    0.000000    0.001394                  None
                              Bicarbonate (50882)    0.000000    0.000103                  None
                                     MCHC (51249)    0.000000    0.005471                  None
                                      MCV (51250)    0.000000    0.002204                  None

In [81]:
SUBJECT_ID = 12592821
HADM_ID = 29232336
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.0364

DEMOGRAPHICS:
  Age: 30
  Gender: Male
  Race: Unknown
  Insurance: UNKNOWN
  LOS: 6 days
  Readmission: No

ADMISSION DETAILS:
  Admission Type: Ew Emer.
  Admission Location: Emergency Room
  Discharge Location: Home

ICD DIAGNOSES (1):
  - Essential (primary) hypertension (I10)

CCSR CATEGORIES (2):
  - Personal/family history of disease (FAC021)
  - Essential hypertension (CIR007)

LAB VALUES (20):
  - Anion Gap (50868): 17.80
  - Bicarbonate (50882): 22.60
  - Calcium (50893): 9.22
  - Chloride (50902): 102.40
  - Creatinine (50912): 0.72
  - Glucose (50931): 81.20
  - Magnesium (50960): 2.14
  - Phosphate (50970): 2.46
  - Potassium (50971): 3.80
  - Sodium (50983): 138.80
  - BUN (51006): 9.00
  - Hematocrit (51221): 40.54
  - Hemoglobin (51222): 13.68
  - MCH (51248): 29.90
  - MCHC (51249): 33.82
  - MCV (51250): 88.60
  - Platelet Count (51265): 236.60
  - RDW (51277): 13.88
  - RBC (51279): 4.58
  - WBC (51301): 11.00

OTHER FEATURES:
  num_diagnoses: 48.00
  num_chronic: 24.00
  comorbidity_score: 2.00
  num_medications_daily: 13.83
  prior_admissions_12mo: 0.00
  cumulative_procedures: 0.00
  cumulative_medications: 51.00
  num_procedures_daily: 0.00

DELTA/SHAP:
                            feature_display  delta_mean  shap_value        interpretation
     Essential (primary) hypertension (I10)   -0.001446   -0.006719         with → ↓ risk
                                WBC (51301)    0.000773    0.015793         high → ↑ risk
                          Phosphate (50970)   -0.000697   -0.020260          low → ↓ risk
                         Creatinine (50912)    0.000259    0.004182          low → ↑ risk
                          Magnesium (50960)   -0.000227   -0.002879         high → ↓ risk
            Essential hypertension (CIR007)    0.000184    0.008606         with → ↑ risk
                                RBC (51279)   -0.000181   -0.041574 normal range → ↓ risk
Personal/family history of disease (FAC021)   -0.000136    0.002558         with → ↓ risk
                        Bicarbonate (50882)   -0.000072   -0.007293 normal range → ↓ risk
                           Chloride (50902)   -0.000059    0.002923 normal range → ↓ risk
                                MCH (51248)    0.000000    0.003279                  None
                                RDW (51277)    0.000000   -0.028548                  None
                     Platelet Count (51265)    0.000000   -0.008642                  None
                                MCV (51250)    0.000000    0.001874                  None
                               MCHC (51249)    0.000000    0.003358                  None
                             Sodium (50983)    0.000000   -0.003323                  None
                         Hemoglobin (51222)    0.000000   -0.034598                  None
                         Hematocrit (51221)    0.000000   -0.054204                  None
                                BUN (51006)    0.000000   -0.000603                  None
                          Anion Gap (50868)    0.000000    0.006896                  None
                            Glucose (50931)    0.000000    0.006223                  None
                            Calcium (50893)    0.000000   -0.006676                  None
                          Potassium (50971)    0.000000   -0.002736                  None

In [82]:
SUBJECT_ID = 11011770
HADM_ID = 28546869
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.4253

DEMOGRAPHICS:
  Age: 30
  Gender: Male
  Race: White
  Insurance: Private
  LOS: 2 days
  Readmission: Yes

ADMISSION DETAILS:
  Admission Type: Observation Admit
  Admission Location: Emergency Room
  Discharge Location: Home

ICD DIAGNOSES (4):
  - Gastroesophageal reflux disease without esophagitis (K219)
  - Major depressive disorder, single episode, unspecified (F329)
  - Anxiety disorder, unspecified (F419)
  - Urinary tract infection, site not specified (N390)

CCSR CATEGORIES (3):
  - Personal/family history of disease (FAC021)
  - Esophageal disorders (DIG004)
  - External cause codes: place of occurrence of the external cause (EXT027)

LAB VALUES (17):
  - Anion Gap (50868): 14.00
  - Bicarbonate (50882): 29.00
  - Chloride (50902): 103.00
  - Creatinine (50912): 0.70
  - Glucose (50931): 75.00
  - Potassium (50971): 3.60
  - Sodium (50983): 142.00
  - BUN (51006): 4.00
  - Hematocrit (51221): 37.20
  - Hemoglobin (51222): 12.30
  - MCH (51248): 28.10
  - MCHC (51249): 33.10
  - MCV (51250): 85.00
  - Platelet Count (51265): 113.00
  - RDW (51277): 14.50
  - RBC (51279): 4.37
  - WBC (51301): 4.90

OTHER FEATURES:
  num_diagnoses: 32.00
  num_chronic: 14.00
  comorbidity_score: 1.00
  num_medications_daily: 18.50
  prior_admissions_12mo: 6.00
  cumulative_procedures: 0.00
  cumulative_medications: 27.50
  num_procedures_daily: 0.00

DELTA/SHAP:
                                                         feature_display  delta_mean  shap_value        interpretation
                                                             BUN (51006)    0.008787    0.022657 normal range → ↑ risk
                                                  Platelet Count (51265)   -0.004061   -0.012817 normal range → ↓ risk
                             Personal/family history of disease (FAC021)   -0.003903    0.001796         with → ↓ risk
                                                      Creatinine (50912)    0.003520    0.003106 normal range → ↑ risk
                                           Esophageal disorders (DIG004)    0.002623    0.003539         with → ↑ risk
                      Urinary tract infection, site not specified (N390)    0.002622    0.010765         with → ↑ risk
                                                      Hemoglobin (51222)    0.002551   -0.012983 normal range → ↑ risk
           Major depressive disorder, single episode, unspecified (F329)    0.002156    0.015736         with → ↑ risk
                                    Anxiety disorder, unspecified (F419)    0.001646    0.009019         with → ↑ risk
                                                             RBC (51279)    0.001534   -0.018318 normal range → ↑ risk
                                                      Hematocrit (51221)    0.000714   -0.017006 normal range → ↑ risk
External cause codes: place of occurrence of the external cause (EXT027)   -0.000290   -0.018410         with → ↓ risk
                                                            MCHC (51249)    0.000000    0.003381                  None
              Gastroesophageal reflux disease without esophagitis (K219)    0.000000   -0.000725                  None
                                                             MCV (51250)    0.000000    0.002698                  None
                                                             MCH (51248)    0.000000   -0.003828                  None
                                                             RDW (51277)    0.000000   -0.016156                  None
                                                       Potassium (50971)    0.000000   -0.002753                  None
                                                          Sodium (50983)    0.000000   -0.017165                  None
                                                         Glucose (50931)    0.000000    0.009435                  None
                                                        Chloride (50902)    0.000000   -0.002129                  None
                                                     Bicarbonate (50882)    0.000000    0.000323                  None
                                                       Anion Gap (50868)    0.000000    0.001625                  None
                                                             WBC (51301)    0.000000   -0.000936                  None

In [83]:
SUBJECT_ID = 18056725
HADM_ID = 25708121
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.1193

DEMOGRAPHICS:
  Age: 32
  Gender: Female
  Race: White
  Insurance: Private
  LOS: 4 days
  Readmission: No

ADMISSION DETAILS:
  Admission Type: Ew Emer.
  Admission Location: Emergency Room
  Discharge Location: Home

ICD DIAGNOSES (2):
  - Personal history of nicotine dependence (Z87891)
  - Anemia, unspecified (D649)

CCSR CATEGORIES (3):
  - Personal/family history of disease (FAC021)
  - Fluid and electrolyte disorders (END011)
  - Aplastic anemia (BLD003)

LAB VALUES (20):
  - Anion Gap (50868): 10.67
  - Bicarbonate (50882): 22.67
  - Calcium (50893): 7.53
  - Chloride (50902): 105.00
  - Creatinine (50912): 0.63
  - Glucose (50931): 128.00
  - Magnesium (50960): 2.17
  - Phosphate (50970): 2.60
  - Potassium (50971): 3.60
  - Sodium (50983): 134.67
  - BUN (51006): 4.00
  - Hematocrit (51221): 26.93
  - Hemoglobin (51222): 9.33
  - MCH (51248): 29.27
  - MCHC (51249): 34.80
  - MCV (51250): 84.00
  - Platelet Count (51265): 252.00
  - RDW (51277): 12.90
  - RBC (51279): 3.19
  - WBC (51301): 9.27

OTHER FEATURES:
  num_diagnoses: 52.00
  num_chronic: 8.00
  comorbidity_score: 0.00
  num_medications_daily: 10.75
  prior_admissions_12mo: 0.00
  cumulative_procedures: 1.00
  cumulative_medications: 21.50
  num_procedures_daily: 0.50

DELTA/SHAP:
                                 feature_display  delta_mean  shap_value        interpretation
                              Hemoglobin (51222)    0.008919    0.020287          low → ↑ risk
                        Aplastic anemia (BLD003)    0.007517    0.050262         with → ↑ risk
                              Hematocrit (51221)    0.007145    0.031218          low → ↑ risk
                                     BUN (51006)    0.007074    0.027790          low → ↑ risk
                                     RBC (51279)    0.005886    0.021059          low → ↑ risk
                               Phosphate (50970)   -0.002300   -0.006708 normal range → ↓ risk
                                  Sodium (50983)    0.001922    0.029433 normal range → ↑ risk
        Fluid and electrolyte disorders (END011)    0.001604    0.018230         with → ↑ risk
                                     WBC (51301)    0.001445   -0.001540 normal range → ↑ risk
     Personal/family history of disease (FAC021)    0.001365    0.004256         with → ↑ risk
Personal history of nicotine dependence (Z87891)    0.001349   -0.000631         with → ↑ risk
                                 Calcium (50893)   -0.001348    0.005608          low → ↓ risk
                                 Glucose (50931)    0.001160   -0.000389 normal range → ↑ risk
                              Creatinine (50912)    0.001155    0.006873          low → ↑ risk
                               Magnesium (50960)   -0.000781   -0.000821 normal range → ↓ risk
                             Bicarbonate (50882)   -0.000594   -0.001863 normal range → ↓ risk
                      Anemia, unspecified (D649)   -0.000414   -0.000746         with → ↓ risk
                               Potassium (50971)    0.000283    0.003380 normal range → ↑ risk
                                Chloride (50902)   -0.000173    0.006151 normal range → ↓ risk
                               Anion Gap (50868)    0.000022   -0.003187 normal range → ↑ risk
                                    MCHC (51249)   -0.000014    0.001974 normal range → ↓ risk
                                     MCH (51248)    0.000000    0.002041                  None
                                     MCV (51250)    0.000000   -0.002589                  None
                          Platelet Count (51265)    0.000000   -0.007086                  None
                                     RDW (51277)    0.000000   -0.094861                  None

### Very elderly

In [84]:
SUBJECT_ID = 10164170
HADM_ID = 24771340
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.2068

DEMOGRAPHICS:
  Age: 87
  Gender: Female
  Race: White - Other European
  Insurance: Medicare
  LOS: 5 days
  Readmission: Yes

ADMISSION DETAILS:
  Admission Type: Urgent
  Admission Location: Transfer From Hospital
  Discharge Location: Home Health Care

ICD DIAGNOSES (3):
  - Atherosclerotic heart disease of native coronary artery without angina pectoris (I2510)
  - Unspecified atrial fibrillation (I4891)
  - Urinary tract infection, site not specified (N390)

CCSR CATEGORIES (4):
  - Personal/family history of disease (FAC021)
  - Coronary atherosclerosis and other heart disease (CIR011)
  - Heart failure (CIR019)
  - Cardiac dysrhythmias (CIR017)

LAB VALUES (20):
  - Anion Gap (50868): 11.00
  - Bicarbonate (50882): 29.40
  - Calcium (50893): 8.56
  - Chloride (50902): 100.80
  - Creatinine (50912): 0.72
  - Glucose (50931): 81.60
  - Magnesium (50960): 1.82
  - Phosphate (50970): 3.12
  - Potassium (50971): 3.82
  - Sodium (50983): 137.40
  - BUN (51006): 15.00
  - Hematocrit (51221): 26.54
  - Hemoglobin (51222): 8.86
  - MCH (51248): 31.74
  - MCHC (51249): 33.40
  - MCV (51250): 95.20
  - Platelet Count (51265): 236.40
  - RDW (51277): 15.16
  - RBC (51279): 2.79
  - WBC (51301): 13.24

OTHER FEATURES:
  num_diagnoses: 100.00
  num_chronic: 35.00
  comorbidity_score: 4.00
  num_medications_daily: 17.60
  prior_admissions_12mo: 0.00
  cumulative_procedures: 0.00
  cumulative_medications: 50.20
  num_procedures_daily: 0.00

DELTA/SHAP:
                                                                        feature_display  delta_mean  shap_value        interpretation
                                                                 Heart failure (CIR019)   -0.024954   -0.053597         with → ↓ risk
                                                                            RDW (51277)    0.024399    0.041942         high → ↑ risk
                                                                     Hematocrit (51221)    0.023048    0.047284          low → ↑ risk
                                                                            RBC (51279)    0.009438    0.030272          low → ↑ risk
                                                                         Sodium (50983)    0.009431    0.005909 normal range → ↑ risk
                                                                            WBC (51301)    0.008560    0.023181         high → ↑ risk
                                                                     Hemoglobin (51222)    0.006025    0.017138          low → ↑ risk
Atherosclerotic heart disease of native coronary artery without angina pectoris (I2510)    0.001397    0.003385         with → ↑ risk
                              Coronary atherosclerosis and other heart disease (CIR011)    0.001058    0.002803         with → ↑ risk
                                                          Cardiac dysrhythmias (CIR017)   -0.000884   -0.002523         with → ↓ risk
                                                                      Magnesium (50960)   -0.000753    0.005499 normal range → ↓ risk
                                                                      Anion Gap (50868)   -0.000744   -0.004993 normal range → ↓ risk
                                            Personal/family history of disease (FAC021)   -0.000454    0.000192         with → ↓ risk
                                                Unspecified atrial fibrillation (I4891)   -0.000287    0.004682         with → ↓ risk
                                                                     Creatinine (50912)    0.000129   -0.004824          low → ↑ risk
                                                                            MCH (51248)   -0.000064    0.005016 normal range → ↓ risk
                                     Urinary tract infection, site not specified (N390)    0.000024    0.003091         with → ↑ risk
                                                                 Platelet Count (51265)    0.000000   -0.018064                  None
                                                                            MCV (51250)    0.000000    0.003974                  None
                                                                           MCHC (51249)    0.000000    0.004921                  None
                                                                    Bicarbonate (50882)    0.000000    0.001764                  None
                                                                        Calcium (50893)    0.000000    0.004351                  None
                                                                      Potassium (50971)    0.000000    0.002225                  None
                                                                      Phosphate (50970)    0.000000    0.002872                  None
                                                                        Glucose (50931)    0.000000    0.005403                  None
                                                                       Chloride (50902)    0.000000    0.003944                  None
                                                                            BUN (51006)    0.000000   -0.016459                  None

In [85]:
SUBJECT_ID = 11698781
HADM_ID = 20902547
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.0712

DEMOGRAPHICS:
  Age: 88
  Gender: Male
  Race: White
  Insurance: Medicare
  LOS: 3 days
  Readmission: No

ADMISSION DETAILS:
  Admission Type: Observation Admit
  Admission Location: Transfer From Hospital
  Discharge Location: Skilled Nursing Facility

ICD DIAGNOSES (1):
  - Personal history of nicotine dependence (Z87891)

CCSR CATEGORIES (2):
  - Personal/family history of disease (FAC021)
  - External cause codes: place of occurrence of the external cause (EXT027)

LAB VALUES (20):
  - Anion Gap (50868): 13.50
  - Bicarbonate (50882): 21.50
  - Calcium (50893): 9.00
  - Chloride (50902): 102.00
  - Creatinine (50912): 0.95
  - Glucose (50931): 115.50
  - Magnesium (50960): 1.90
  - Phosphate (50970): 2.20
  - Potassium (50971): 3.80
  - Sodium (50983): 137.00
  - BUN (51006): 20.50
  - Hematocrit (51221): 41.25
  - Hemoglobin (51222): 13.05
  - MCH (51248): 31.35
  - MCHC (51249): 31.65
  - MCV (51250): 99.00
  - Platelet Count (51265): 115.00
  - RDW (51277): 14.85
  - RBC (51279): 4.17
  - WBC (51301): 19.45

OTHER FEATURES:
  num_diagnoses: 33.00
  num_chronic: 15.00
  comorbidity_score: 0.00
  num_medications_daily: 10.33
  prior_admissions_12mo: 0.00
  cumulative_procedures: 1.00
  cumulative_medications: 20.00
  num_procedures_daily: 0.33

DELTA/SHAP:
                                                         feature_display  delta_mean  shap_value        interpretation
External cause codes: place of occurrence of the external cause (EXT027)   -0.016425   -0.095118         with → ↓ risk
                                                             RDW (51277)    0.008400    0.027685         high → ↑ risk
                                                             WBC (51301)    0.006192    0.056806         high → ↑ risk
                                                  Platelet Count (51265)   -0.003417   -0.026707          low → ↓ risk
                                                             RBC (51279)   -0.001623   -0.018295          low → ↓ risk
                        Personal history of nicotine dependence (Z87891)   -0.001182   -0.010772         with → ↓ risk
                                                         Glucose (50931)    0.000549   -0.003731         high → ↑ risk
                                                       Phosphate (50970)   -0.000482   -0.007921          low → ↓ risk
                             Personal/family history of disease (FAC021)    0.000164    0.001748         with → ↑ risk
                                                     Bicarbonate (50882)   -0.000083   -0.002437 normal range → ↓ risk
                                                      Hemoglobin (51222)   -0.000047   -0.015937 normal range → ↓ risk
                                                        Chloride (50902)    0.000000    0.001196                  None
                                                            MCHC (51249)    0.000000    0.000891                  None
                                                       Anion Gap (50868)    0.000000    0.002852                  None
                                                         Calcium (50893)    0.000000   -0.004587                  None
                                                             MCV (51250)    0.000000    0.002309                  None
                                                      Hematocrit (51221)    0.000000   -0.024890                  None
                                                             MCH (51248)    0.000000    0.003648                  None
                                                      Creatinine (50912)    0.000000   -0.002597                  None
                                                             BUN (51006)    0.000000   -0.001111                  None
                                                          Sodium (50983)    0.000000    0.002436                  None
                                                       Magnesium (50960)    0.000000    0.000895                  None
                                                       Potassium (50971)    0.000000   -0.000486                  None

In [86]:
SUBJECT_ID = 16668434
HADM_ID = 23499682
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.1015

DEMOGRAPHICS:
  Age: 80
  Gender: Female
  Race: White
  Insurance: Medicare
  LOS: 6 days
  Readmission: No

ADMISSION DETAILS:
  Admission Type: Ew Emer.
  Admission Location: Transfer From Hospital
  Discharge Location: Hospice

ICD DIAGNOSES (2):
  - Essential (primary) hypertension (I10)
  - Urinary tract infection, site not specified (N390)

CCSR CATEGORIES (3):
  - Other specified status (FAC025)
  - Essential hypertension (CIR007)
  - External cause codes: place of occurrence of the external cause (EXT027)

LAB VALUES (20):
  - Anion Gap (50868): 10.80
  - Bicarbonate (50882): 20.40
  - Calcium (50893): 9.14
  - Chloride (50902): 108.40
  - Creatinine (50912): 1.12
  - Glucose (50931): 135.00
  - Magnesium (50960): 2.24
  - Phosphate (50970): 2.88
  - Potassium (50971): 4.00
  - Sodium (50983): 139.60
  - BUN (51006): 17.80
  - Hematocrit (51221): 32.38
  - Hemoglobin (51222): 10.02
  - MCH (51248): 29.28
  - MCHC (51249): 30.98
  - MCV (51250): 94.60
  - Platelet Count (51265): 268.20
  - RDW (51277): 13.80
  - RBC (51279): 3.42
  - WBC (51301): 12.68

OTHER FEATURES:
  num_diagnoses: 144.00
  num_chronic: 60.00
  comorbidity_score: 7.00
  num_medications_daily: 22.17
  prior_admissions_12mo: 0.00
  cumulative_procedures: 0.50
  cumulative_medications: 64.50
  num_procedures_daily: 0.17

DELTA/SHAP:
                                                         feature_display  delta_mean  shap_value        interpretation
External cause codes: place of occurrence of the external cause (EXT027)   -0.008691   -0.044889         with → ↓ risk
                                                             WBC (51301)    0.005809    0.030569         high → ↑ risk
                                                     Bicarbonate (50882)    0.005275    0.012128 normal range → ↑ risk
                                                      Hematocrit (51221)   -0.004324    0.000134          low → ↓ risk
                                                         Glucose (50931)    0.002010    0.006851         high → ↑ risk
                                                             RBC (51279)    0.001749    0.004754          low → ↑ risk
                                                      Hemoglobin (51222)    0.001017    0.006002          low → ↑ risk
                                         Other specified status (FAC025)   -0.000809   -0.001559         with → ↓ risk
                      Urinary tract infection, site not specified (N390)   -0.000497    0.001087         with → ↓ risk
                                                        Chloride (50902)    0.000417   -0.002417         high → ↑ risk
                                                       Magnesium (50960)    0.000234   -0.000448 normal range → ↑ risk
                                  Essential (primary) hypertension (I10)   -0.000133   -0.001948         with → ↓ risk
                                                       Potassium (50971)    0.000061    0.000453 normal range → ↑ risk
                                                      Creatinine (50912)    0.000000   -0.000252                  None
                                                          Sodium (50983)    0.000000   -0.028341                  None
                                                             BUN (51006)    0.000000   -0.009167                  None
                                                         Calcium (50893)    0.000000   -0.001540                  None
                                                       Anion Gap (50868)    0.000000   -0.002783                  None
                                                             MCH (51248)    0.000000    0.004724                  None
                                                            MCHC (51249)    0.000000    0.002826                  None
                                                             MCV (51250)    0.000000    0.003207                  None
                                                  Platelet Count (51265)    0.000000    0.000104                  None
                                                             RDW (51277)    0.000000   -0.017197                  None
                                         Essential hypertension (CIR007)    0.000000    0.003353                  None
                                                       Phosphate (50970)    0.000000    0.001188                  None

In [87]:
SUBJECT_ID = 19972786
HADM_ID = 29611193
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.2264

DEMOGRAPHICS:
  Age: 81
  Gender: Male
  Race: Black/African American
  Insurance: Medicare
  LOS: 4 days
  Readmission: Yes

ADMISSION DETAILS:
  Admission Type: Ew Emer.
  Admission Location: Emergency Room
  Discharge Location: Home Health Care

ICD DIAGNOSES (1):
  - Hyperlipidemia, unspecified (E785)

CCSR CATEGORIES (7):
  - Personal/family history of disease (FAC021)
  - Other specified status (FAC025)
  - Fluid and electrolyte disorders (END011)
  - Disorders of lipid metabolism (END010)
  - Diabetes mellitus with complication (END003)
  - Heart failure (CIR019)
  - Hypertension with complications and secondary hypertension (CIR008)

LAB VALUES (20):
  - Anion Gap (50868): 13.33
  - Bicarbonate (50882): 27.67
  - Calcium (50893): 9.73
  - Chloride (50902): 93.67
  - Creatinine (50912): 1.13
  - Glucose (50931): 118.33
  - Magnesium (50960): 1.97
  - Phosphate (50970): 3.33
  - Potassium (50971): 4.57
  - Sodium (50983): 130.33
  - BUN (51006): 15.67
  - Hematocrit (51221): 36.10
  - Hemoglobin (51222): 11.90
  - MCH (51248): 31.93
  - MCHC (51249): 32.97
  - MCV (51250): 96.67
  - Platelet Count (51265): 214.33
  - RDW (51277): 14.23
  - RBC (51279): 3.73
  - WBC (51301): 4.23

OTHER FEATURES:
  num_diagnoses: 48.00
  num_chronic: 32.00
  comorbidity_score: 4.00
  num_medications_daily: 14.75
  prior_admissions_12mo: 1.00
  cumulative_procedures: 0.00
  cumulative_medications: 31.00
  num_procedures_daily: 0.00

DELTA/SHAP:
                                                    feature_display  delta_mean  shap_value        interpretation
                                                     Sodium (50983)    0.031752    0.095460          low → ↑ risk
                                             Heart failure (CIR019)   -0.018798   -0.043485         with → ↓ risk
                                 Hyperlipidemia, unspecified (E785)   -0.016268   -0.032469         with → ↓ risk
                           Fluid and electrolyte disorders (END011)    0.011700    0.029977         with → ↑ risk
                       Diabetes mellitus with complication (END003)   -0.007506   -0.021725         with → ↓ risk
Hypertension with complications and secondary hypertension (CIR008)   -0.006051   -0.010838         with → ↓ risk
                                                        RBC (51279)    0.005719   -0.005916          low → ↑ risk
                                    Other specified status (FAC025)   -0.004015    0.000184         with → ↓ risk
                             Disorders of lipid metabolism (END010)   -0.003813   -0.013298         with → ↓ risk
                                                 Hematocrit (51221)    0.001172   -0.040169          low → ↑ risk
                                                 Hemoglobin (51222)   -0.000955   -0.020420          low → ↓ risk
                                                        MCH (51248)    0.000910    0.004376 normal range → ↑ risk
                                                   Chloride (50902)    0.000851    0.006763 normal range → ↑ risk
                        Personal/family history of disease (FAC021)    0.000805    0.000953         with → ↑ risk
                                                        WBC (51301)    0.000411   -0.002285 normal range → ↑ risk
                                                  Magnesium (50960)   -0.000248    0.001213 normal range → ↓ risk
                                                    Glucose (50931)   -0.000019   -0.002194         high → ↓ risk
                                                  Phosphate (50970)    0.000000    0.001533                  None
                                                  Potassium (50971)    0.000000    0.000543                  None
                                                        BUN (51006)    0.000000   -0.009308                  None
                                                 Creatinine (50912)    0.000000   -0.002226                  None
                                                    Calcium (50893)    0.000000   -0.007926                  None
                                                Bicarbonate (50882)    0.000000   -0.000351                  None
                                                       MCHC (51249)    0.000000    0.003060                  None
                                                        MCV (51250)    0.000000    0.003363                  None
                                             Platelet Count (51265)    0.000000   -0.016470                  None
                                                        RDW (51277)    0.000000   -0.029606                  None
                                                  Anion Gap (50868)    0.000000    0.000998                  None

### Elderly

In [88]:
SUBJECT_ID = 19622090
HADM_ID = 25925869
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.3821

DEMOGRAPHICS:
  Age: 75
  Gender: Female
  Race: White
  Insurance: Medicare
  LOS: 4 days
  Readmission: Yes

ADMISSION DETAILS:
  Admission Type: Observation Admit
  Admission Location: Emergency Room
  Discharge Location: Home Health Care

ICD DIAGNOSES (3):
  - Gastroesophageal reflux disease without esophagitis (K219)
  - Type 2 diabetes mellitus without complications (E119)
  - Urinary tract infection, site not specified (N390)

CCSR CATEGORIES (3):
  - Personal/family history of disease (FAC021)
  - Heart failure (CIR019)
  - Esophageal disorders (DIG004)

LAB VALUES (20):
  - Anion Gap (50868): 12.67
  - Bicarbonate (50882): 29.33
  - Calcium (50893): 8.70
  - Chloride (50902): 102.67
  - Creatinine (50912): 1.30
  - Glucose (50931): 150.00
  - Magnesium (50960): 2.17
  - Phosphate (50970): 4.13
  - Potassium (50971): 4.13
  - Sodium (50983): 140.67
  - BUN (51006): 36.00
  - Hematocrit (51221): 24.57
  - Hemoglobin (51222): 8.00
  - MCH (51248): 31.20
  - MCHC (51249): 32.60
  - MCV (51250): 95.67
  - Platelet Count (51265): 52.33
  - RDW (51277): 14.07
  - RBC (51279): 2.57
  - WBC (51301): 2.90

OTHER FEATURES:
  num_diagnoses: 60.00
  num_chronic: 36.00
  comorbidity_score: 3.00
  num_medications_daily: 26.75
  prior_admissions_12mo: 3.00
  cumulative_procedures: 0.25
  cumulative_medications: 64.00
  num_procedures_daily: 0.25

DELTA/SHAP:
                                           feature_display  delta_mean  shap_value interpretation
                                    Platelet Count (51265)    0.046284    0.128638   low → ↑ risk
                                               RBC (51279)    0.038939    0.057684   low → ↑ risk
                                        Hematocrit (51221)    0.032680    0.045260   low → ↑ risk
                                    Heart failure (CIR019)   -0.012154   -0.036240  with → ↓ risk
                                        Hemoglobin (51222)    0.009036    0.014396   low → ↑ risk
                                               WBC (51301)    0.007695    0.016374   low → ↑ risk
                                               BUN (51006)    0.006652    0.023289  high → ↑ risk
               Personal/family history of disease (FAC021)   -0.004213   -0.002836  with → ↓ risk
     Type 2 diabetes mellitus without complications (E119)    0.002767    0.008400  with → ↑ risk
                                         Magnesium (50960)   -0.001105   -0.001848  high → ↓ risk
                                           Glucose (50931)    0.000840    0.002808  high → ↑ risk
                             Esophageal disorders (DIG004)    0.000477    0.002001  with → ↑ risk
Gastroesophageal reflux disease without esophagitis (K219)    0.000280   -0.000198  with → ↑ risk
                                        Creatinine (50912)    0.000000    0.000618           None
                                         Potassium (50971)    0.000000    0.000912           None
                                            Sodium (50983)    0.000000   -0.020191           None
                                          Chloride (50902)    0.000000    0.000255           None
                                           Calcium (50893)    0.000000    0.002017           None
                                       Bicarbonate (50882)    0.000000    0.000359           None
                                               MCH (51248)    0.000000    0.004300           None
                                              MCHC (51249)    0.000000    0.001613           None
                                               MCV (51250)    0.000000    0.001393           None
                                         Anion Gap (50868)    0.000000    0.000381           None
                                               RDW (51277)    0.000000   -0.036119           None
        Urinary tract infection, site not specified (N390)    0.000000    0.002983           None
                                         Phosphate (50970)    0.000000    0.001722           None

In [89]:
SUBJECT_ID = 11618742
HADM_ID = 28081676
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.4399

DEMOGRAPHICS:
  Age: 76
  Gender: Male
  Race: White
  Insurance: Medicare
  LOS: 9 days
  Readmission: Yes

ADMISSION DETAILS:
  Admission Type: Direct Emer.
  Admission Location: Physician Referral
  Discharge Location: Home

ICD DIAGNOSES (3):
  - Hyperlipidemia, unspecified (E785)
  - Acute kidney failure, unspecified (N179)
  - Long term (current) use of insulin (Z794)

CCSR CATEGORIES (9):
  - Other specified status (FAC025)
  - Coronary atherosclerosis and other heart disease (CIR011)
  - Disorders of lipid metabolism (END010)
  - Diabetes mellitus with complication (END003)
  - Heart failure (CIR019)
  - Cardiac dysrhythmias (CIR017)
  - Hypertension with complications and secondary hypertension (CIR008)
  - External cause codes: place of occurrence of the external cause (EXT027)
  - Acute and unspecified renal failure (GEN002)

LAB VALUES (20):
  - Anion Gap (50868): 14.22
  - Bicarbonate (50882): 27.00
  - Calcium (50893): 8.88
  - Chloride (50902): 100.11
  - Creatinine (50912): 2.28
  - Glucose (50931): 167.22
  - Magnesium (50960): 2.43
  - Phosphate (50970): 4.53
  - Potassium (50971): 4.11
  - Sodium (50983): 141.33
  - BUN (51006): 88.89
  - Hematocrit (51221): 27.86
  - Hemoglobin (51222): 8.66
  - MCH (51248): 32.14
  - MCHC (51249): 31.09
  - MCV (51250): 103.44
  - Platelet Count (51265): 123.78
  - RDW (51277): 17.49
  - RBC (51279): 2.69
  - WBC (51301): 8.41

OTHER FEATURES:
  num_diagnoses: 189.00
  num_chronic: 117.00
  comorbidity_score: 4.00
  num_medications_daily: 23.22
  prior_admissions_12mo: 5.00
  cumulative_procedures: 3.33
  cumulative_medications: 105.00
  num_procedures_daily: 0.67

DELTA/SHAP:
                                                         feature_display  delta_mean  shap_value        interpretation
                                                             RDW (51277)    0.073333    0.130305         high → ↑ risk
                                                             RBC (51279)    0.024623    0.042365          low → ↑ risk
                                                      Hematocrit (51221)    0.019205    0.037814          low → ↑ risk
                            Diabetes mellitus with complication (END003)   -0.015136   -0.038929         with → ↓ risk
                                                  Heart failure (CIR019)   -0.012627   -0.040867         with → ↓ risk
                                                             BUN (51006)    0.009410    0.043781         high → ↑ risk
                                         Other specified status (FAC025)   -0.007749   -0.002037         with → ↓ risk
     Hypertension with complications and secondary hypertension (CIR008)   -0.007550   -0.012450         with → ↓ risk
                                                      Hemoglobin (51222)    0.005130    0.015170          low → ↑ risk
                                                  Platelet Count (51265)    0.004861   -0.009764          low → ↑ risk
                                                             MCH (51248)    0.004669    0.018122         high → ↑ risk
                                           Cardiac dysrhythmias (CIR017)   -0.003111   -0.006236         with → ↓ risk
                                      Hyperlipidemia, unspecified (E785)   -0.002881   -0.013117         with → ↓ risk
                                                         Glucose (50931)    0.002200    0.008805         high → ↑ risk
               Coronary atherosclerosis and other heart disease (CIR011)    0.001228    0.001365         with → ↑ risk
                                                       Magnesium (50960)   -0.001208   -0.002319         high → ↓ risk
                            Acute and unspecified renal failure (GEN002)    0.001169    0.005952         with → ↑ risk
                                                      Creatinine (50912)    0.001108    0.006003         high → ↑ risk
External cause codes: place of occurrence of the external cause (EXT027)   -0.000843   -0.015465         with → ↓ risk
                                                             MCV (51250)    0.000648    0.002562         high → ↑ risk
                                  Disorders of lipid metabolism (END010)   -0.000522   -0.007470         with → ↓ risk
                                                             WBC (51301)    0.000257   -0.011428 normal range → ↑ risk
                               Long term (current) use of insulin (Z794)   -0.000094    0.000564         with → ↓ risk
                                Acute kidney failure, unspecified (N179)    0.000062    0.003878         with → ↑ risk
                                                       Phosphate (50970)   -0.000009    0.001705         high → ↓ risk
                                                       Potassium (50971)    0.000000    0.003268                  None
                                                          Sodium (50983)    0.000000   -0.018888                  None
                                                        Chloride (50902)    0.000000    0.003927                  None
                                                         Calcium (50893)    0.000000   -0.000846                  None
                                                     Bicarbonate (50882)    0.000000    0.000130                  None
                                                       Anion Gap (50868)    0.000000    0.002251                  None
                                                            MCHC (51249)    0.000000   -0.010146                  None

In [90]:
SUBJECT_ID = 17780345
HADM_ID = 26440784
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.1174

DEMOGRAPHICS:
  Age: 71
  Gender: Female
  Race: White
  Insurance: Medicare
  LOS: 3 days
  Readmission: No

ADMISSION DETAILS:
  Admission Type: Observation Admit
  Admission Location: Transfer From Hospital
  Discharge Location: Home

ICD DIAGNOSES (1):
  - Atherosclerotic heart disease of native coronary artery without angina pectoris (I2510)

CCSR CATEGORIES (5):
  - Other specified status (FAC025)
  - Fluid and electrolyte disorders (END011)
  - Coronary atherosclerosis and other heart disease (CIR011)
  - Heart failure (CIR019)
  - Hypertension with complications and secondary hypertension (CIR008)

LAB VALUES (20):
  - Anion Gap (50868): 12.00
  - Bicarbonate (50882): 28.00
  - Calcium (50893): 9.05
  - Chloride (50902): 102.50
  - Creatinine (50912): 0.50
  - Glucose (50931): 106.00
  - Magnesium (50960): 1.90
  - Phosphate (50970): 3.40
  - Potassium (50971): 4.50
  - Sodium (50983): 142.50
  - BUN (51006): 8.00
  - Hematocrit (51221): 36.95
  - Hemoglobin (51222): 11.50
  - MCH (51248): 29.25
  - MCHC (51249): 31.15
  - MCV (51250): 94.00
  - Platelet Count (51265): 181.00
  - RDW (51277): 13.35
  - RBC (51279): 3.94
  - WBC (51301): 4.20

OTHER FEATURES:
  num_diagnoses: 45.00
  num_chronic: 21.00
  comorbidity_score: 2.00
  num_medications_daily: 10.67
  prior_admissions_12mo: 1.00
  cumulative_procedures: 0.00
  cumulative_medications: 20.33
  num_procedures_daily: 0.00

DELTA/SHAP:
                                                                        feature_display  delta_mean  shap_value        interpretation
                                                                 Heart failure (CIR019)   -0.005336   -0.042261         with → ↓ risk
                                               Fluid and electrolyte disorders (END011)    0.004301    0.024698         with → ↑ risk
Atherosclerotic heart disease of native coronary artery without angina pectoris (I2510)    0.002189    0.006117         with → ↑ risk
                                                                            RBC (51279)    0.001773   -0.026079 normal range → ↑ risk
                    Hypertension with complications and secondary hypertension (CIR008)   -0.001207   -0.008267         with → ↓ risk
                                                                            WBC (51301)    0.001050   -0.003100 normal range → ↑ risk
                              Coronary atherosclerosis and other heart disease (CIR011)    0.001011    0.005921         with → ↑ risk
                                                                            BUN (51006)    0.000910   -0.004138 normal range → ↑ risk
                                                                     Hemoglobin (51222)    0.000898   -0.021933          low → ↑ risk
                                                                     Hematocrit (51221)    0.000531   -0.051920 normal range → ↑ risk
                                                        Other specified status (FAC025)    0.000504    0.003904         with → ↑ risk
                                                                        Glucose (50931)    0.000218   -0.004097 normal range → ↑ risk
                                                                     Creatinine (50912)   -0.000198   -0.000856          low → ↓ risk
                                                                            RDW (51277)    0.000000   -0.061488                  None
                                                                 Platelet Count (51265)    0.000000   -0.026839                  None
                                                                            MCV (51250)    0.000000    0.003355                  None
                                                                           MCHC (51249)    0.000000    0.000551                  None
                                                                            MCH (51248)    0.000000    0.003284                  None
                                                                      Anion Gap (50868)    0.000000   -0.000583                  None
                                                                    Bicarbonate (50882)    0.000000    0.000150                  None
                                                                         Sodium (50983)    0.000000   -0.034698                  None
                                                                      Potassium (50971)    0.000000    0.001510                  None
                                                                      Magnesium (50960)    0.000000    0.004140                  None
                                                                       Chloride (50902)    0.000000    0.001234                  None
                                                                        Calcium (50893)    0.000000   -0.000140                  None
                                                                      Phosphate (50970)    0.000000    0.001759                  None

In [91]:
SUBJECT_ID = 14507136
HADM_ID = 28573487
clean_data = get_patient_full_data_with_analysis(
    SUBJECT_ID, HADM_ID, total_data)
print_patient_full_with_analysis(clean_data)

Actual risk: 0.0498

DEMOGRAPHICS:
  Age: 66
  Gender: Male
  Race: Unknown
  Insurance: Medicare
  LOS: 4 days
  Readmission: No

ADMISSION DETAILS:
  Admission Type: Observation Admit
  Admission Location: Physician Referral
  Discharge Location: Rehab

ICD DIAGNOSES (4):
  - Essential (primary) hypertension (I10)
  - Hyperlipidemia, unspecified (E785)
  - Gastroesophageal reflux disease without esophagitis (K219)
  - Personal history of nicotine dependence (Z87891)

CCSR CATEGORIES (5):
  - Personal/family history of disease (FAC021)
  - Disorders of lipid metabolism (END010)
  - Essential hypertension (CIR007)
  - Esophageal disorders (DIG004)
  - External cause codes: place of occurrence of the external cause (EXT027)

LAB VALUES (20):
  - Anion Gap (50868): 13.00
  - Bicarbonate (50882): 28.00
  - Calcium (50893): 8.70
  - Chloride (50902): 98.67
  - Creatinine (50912): 0.80
  - Glucose (50931): 115.33
  - Magnesium (50960): 2.00
  - Phosphate (50970): 3.47
  - Potassium (50971): 4.30
  - Sodium (50983): 135.33
  - BUN (51006): 12.00
  - Hematocrit (51221): 30.10
  - Hemoglobin (51222): 9.33
  - MCH (51248): 29.43
  - MCHC (51249): 31.03
  - MCV (51250): 95.00
  - Platelet Count (51265): 296.67
  - RDW (51277): 13.53
  - RBC (51279): 3.17
  - WBC (51301): 8.10

OTHER FEATURES:
  num_diagnoses: 60.00
  num_chronic: 12.00
  comorbidity_score: 0.00
  num_medications_daily: 16.75
  prior_admissions_12mo: 1.00
  cumulative_procedures: 5.00
  cumulative_medications: 41.50
  num_procedures_daily: 1.25

DELTA/SHAP:
                                                         feature_display  delta_mean  shap_value        interpretation
                        Personal history of nicotine dependence (Z87891)   -0.002630   -0.027539         with → ↓ risk
              Gastroesophageal reflux disease without esophagitis (K219)   -0.001460   -0.003480         with → ↓ risk
                                                             RBC (51279)    0.001214    0.018626          low → ↑ risk
                                      Hyperlipidemia, unspecified (E785)   -0.000772   -0.023214         with → ↓ risk
                                                      Hematocrit (51221)    0.000735    0.009449          low → ↑ risk
                                                      Hemoglobin (51222)    0.000572    0.010754          low → ↑ risk
                                                          Sodium (50983)    0.000549    0.017221 normal range → ↑ risk
External cause codes: place of occurrence of the external cause (EXT027)    0.000467   -0.011015         with → ↑ risk
                             Personal/family history of disease (FAC021)    0.000414    0.004115         with → ↑ risk
                                  Disorders of lipid metabolism (END010)   -0.000318   -0.011024         with → ↓ risk
                                           Esophageal disorders (DIG004)    0.000262    0.004542         with → ↑ risk
                                  Essential (primary) hypertension (I10)   -0.000239   -0.003724         with → ↓ risk
                                                         Glucose (50931)    0.000097   -0.002447 normal range → ↑ risk
                                                         Calcium (50893)    0.000059    0.001987 normal range → ↑ risk
                                                       Magnesium (50960)    0.000033    0.000856 normal range → ↑ risk
                                                      Creatinine (50912)    0.000000   -0.001448                  None
                                                        Chloride (50902)    0.000000    0.003060                  None
                                                       Phosphate (50970)    0.000000    0.001453                  None
                                                       Potassium (50971)    0.000000    0.001496                  None
                                                             BUN (51006)    0.000000   -0.012228                  None
                                                     Bicarbonate (50882)    0.000000    0.003236                  None
                                                       Anion Gap (50868)    0.000000   -0.000196                  None
                                                             MCH (51248)    0.000000    0.004963                  None
                                                            MCHC (51249)    0.000000   -0.004411                  None
                                                             MCV (51250)    0.000000    0.003327                  None
                                                  Platelet Count (51265)    0.000000    0.004627                  None
                                                             RDW (51277)    0.000000   -0.061310                  None
                                         Essential hypertension (CIR007)    0.000000    0.003015                  None
                                                             WBC (51301)    0.000000   -0.020857                  None